// This is a skeleton starter React page generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PageParamsProvider as PageParamsProvider__ } from "@plasmicapp/react-web/lib/host";

import {
  PlasmicMissionsEditable,
  PlasmicMissionsEditable__HeadOptions
} from "../../components/plasmic-linked/kaizen/PlasmicMissionsEditable";
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/missions-editable/")({
  head: () => ({
    meta: [...PlasmicMissionsEditable__HeadOptions.meta],
    links: [...PlasmicMissionsEditable__HeadOptions.links]
  }),
  component: MissionsEditable
});

function MissionsEditable() {
  // Use PlasmicMissionsEditable to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicMissionsEditable are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, PlasmicMissionsEditable is wrapped by your project's global
  // variant context providers. These wrappers may be moved to
  // TanStack Router __root Route
  // (https://tanstack.com/router/latest/docs/framework/react/guide/tanstack-start#the-root-of-your-application).

  return (
    <PageParamsProvider__
      route={Route.fullPath}
      params={Route.useParams()}
      query={Route.useSearch()}
    >
      <PlasmicMissionsEditable />
    </PageParamsProvider__>
  );
}

export default MissionsEditable;
