/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: axVArpcqgHCPMKB2yUGsW3

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: axVArpcqgHCPMKB2yUGsW3/projectModule

import "./plasmic.css"; // plasmic-import: axVArpcqgHCPMKB2yUGsW3/projectcss

const data = {
  base: `${"plasmic_tokens_axVArpcqgHCPMKB2yUGsW3"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
