/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4WZ4je7EqYHVjfVVU6jztT
// Component: SAnHGD-LIu0q

import * as React from "react";

import { useRouter, Link } from "@tanstack/react-router";
import type { LinkProps } from "@tanstack/react-router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";
import "../../plasmic/plasmic__default_style.css"; // plasmic-import: global/defaultcss

import "./plasmic.css"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/projectcss
import "./PlasmicDashboardNative.css"; // plasmic-import: SAnHGD-LIu0q/css

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicDashboardNative__VariantMembers = {};
export type PlasmicDashboardNative__VariantsArgs = {};
type VariantPropType = keyof PlasmicDashboardNative__VariantsArgs;
export const PlasmicDashboardNative__VariantProps =
  new Array<VariantPropType>();

export type PlasmicDashboardNative__ArgsType = {};
type ArgPropType = keyof PlasmicDashboardNative__ArgsType;
export const PlasmicDashboardNative__ArgProps = new Array<ArgPropType>();

export type PlasmicDashboardNative__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<"header">;
  nav?: Flex__<"nav">;
  main?: Flex__<"main">;
  h1?: Flex__<"h1">;
  footer?: Flex__<"footer">;
};

export interface DefaultDashboardNativeProps {}

const $$ = {};

function useTanStackRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDashboardNative__RenderFunc(props: {
  variants: PlasmicDashboardNative__VariantsArgs;
  args: PlasmicDashboardNative__ArgsType;
  overrides: PlasmicDashboardNative__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __tanstackRouter = useTanStackRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "plasmic_default__all",
            "root_reset_4WZ4je7EqYHVjfVVU6jztT",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            "DashboardNative__root__ueeHy"
          )}
        >
          <div
            className={classNames(
              "plasmic_default__all",
              "DashboardNative__freeBox__wlUh4"
            )}
          >
            <header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames(
                "plasmic_default__all",
                "DashboardNative__header__xa7I0"
              )}
            >
              <strong
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__strong",
                  "plasmic_default__strong__4WZ4j",
                  "__wab_text",
                  "DashboardNative__strong__eL8V4"
                )}
              >
                {"kaizen"}
              </strong>
              <nav
                data-plasmic-name={"nav"}
                data-plasmic-override={overrides.nav}
                className={classNames(
                  "plasmic_default__all",
                  "DashboardNative__nav__oJlPr"
                )}
              >
                <PlasmicLink__
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__a",
                    "plasmic_default__a__4WZ4j",
                    "__wab_text",
                    "DashboardNative__link__jGqwl"
                  )}
                  component={Link}
                  href={"/dashboard"}
                  platform={"tanstack"}
                >
                  {"Vis\u00e3o geral"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__a",
                    "plasmic_default__a__4WZ4j",
                    "__wab_text",
                    "DashboardNative__link__xbQBs"
                  )}
                  component={Link}
                  href={"/tasks"}
                  platform={"tanstack"}
                >
                  {"Miss\u00f5es"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__a",
                    "plasmic_default__a__4WZ4j",
                    "__wab_text",
                    "DashboardNative__link__sl8Iz"
                  )}
                  component={Link}
                  href={"/character"}
                  platform={"tanstack"}
                >
                  {"Personagem"}
                </PlasmicLink__>
              </nav>
              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "__wab_text",
                  "DashboardNative__span___96Jz0"
                )}
              >
                {"EMBER \u03b1"}
              </span>
            </header>
            <main
              data-plasmic-name={"main"}
              data-plasmic-override={overrides.main}
              className={classNames(
                "plasmic_default__all",
                "DashboardNative__main__xNwz4"
              )}
            >
              <div
                className={classNames(
                  "plasmic_default__all",
                  "DashboardNative__freeBox__fiNI"
                )}
              >
                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "__wab_text",
                    "DashboardNative__span__m9Rn2"
                  )}
                >
                  {"UM NOVO DIA. UM POUCO MAIS LONGE."}
                </span>
              </div>
              <div
                className={classNames(
                  "plasmic_default__all",
                  "DashboardNative__freeBox__sgaiJ"
                )}
              >
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__h1",
                    "plasmic_default__h1__4WZ4j",
                    "__wab_text",
                    "DashboardNative__h1__qS0Hl"
                  )}
                >
                  {"Sua pr\u00f3xima vers\u00e3o come\u00e7a aqui."}
                </h1>
                <p
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__p",
                    "plasmic_default__p__4WZ4j",
                    "__wab_text",
                    "DashboardNative__p__ostzV"
                  )}
                >
                  {"Ol\u00e1, Alex. Toda pequena conquista conta."}
                </p>
              </div>
              <div
                className={classNames(
                  "plasmic_default__all",
                  "DashboardNative__freeBox___7VJ7"
                )}
              >
                <section
                  className={classNames(
                    "plasmic_default__all",
                    "DashboardNative__section__ll2C"
                  )}
                >
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "DashboardNative__freeBox__wZMrE"
                    )}
                  >
                    <h2
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__h2",
                        "plasmic_default__h2__4WZ4j",
                        "__wab_text",
                        "DashboardNative__h2___0O3Is"
                      )}
                    >
                      {"personagem.exe"}
                    </h2>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span__aVuUk"
                      )}
                    >
                      {"01"}
                    </span>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "DashboardNative__freeBox__xoLbY"
                    )}
                  >
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "DashboardNative__freeBox__vA47"
                      )}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "DashboardNative__span__skeZg"
                        )}
                      >
                        {"AVENTUREIRO EM EVOLU\u00c7\u00c3O"}
                      </span>
                    </div>
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "DashboardNative__freeBox__a83V"
                      )}
                    >
                      <div
                        className={classNames(
                          "plasmic_default__all",
                          "DashboardNative__freeBox__to6Tc"
                        )}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "DashboardNative__span___5Swyo"
                          )}
                        >
                          {"SEU PERSONAGEM"}
                        </span>
                      </div>
                      <h2
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__h2",
                          "plasmic_default__h2__4WZ4j",
                          "__wab_text",
                          "DashboardNative__h2___5MMn"
                        )}
                      >
                        {"Alex"}
                      </h2>
                      <p
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__p",
                          "plasmic_default__p__4WZ4j",
                          "__wab_text",
                          "DashboardNative__p__sbaK"
                        )}
                      >
                        {"Aventureiro \u00b7 Jornada pessoal"}
                      </p>
                      <div
                        className={classNames(
                          "plasmic_default__all",
                          "DashboardNative__freeBox__md746"
                        )}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "DashboardNative__span__w3ADs"
                          )}
                        >
                          {"N\u00cdVEL 02 \u00b7 LVL"}
                        </span>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "DashboardNative__freeBox__q6F9W"
                    )}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span__wdNgD"
                      )}
                    >
                      {"For\u00e7a 05"}
                    </span>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span__gOwva"
                      )}
                    >
                      {"Intelig\u00eancia 07"}
                    </span>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span___1EDyf"
                      )}
                    >
                      {"Disciplina 06"}
                    </span>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span__r68Wx"
                      )}
                    >
                      {"Criatividade 04"}
                    </span>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span__gVmnw"
                      )}
                    >
                      {"Resili\u00eancia 05"}
                    </span>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "DashboardNative__freeBox__ycKWs"
                    )}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span__imEx"
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <strong
                            className={classNames(
                              "plasmic_default__all",
                              "plasmic_default__strong",
                              "plasmic_default__strong__4WZ4j",
                              "__wab_text",
                              "plasmic_default__inline",
                              "DashboardNative__strong__d37Hy"
                            )}
                          >
                            {"85"}
                          </strong>
                        }
                        <React.Fragment>{" moedas"}</React.Fragment>
                      </React.Fragment>
                    </span>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span__ayWu2"
                      )}
                    >
                      <React.Fragment>
                        <React.Fragment>{""}</React.Fragment>
                        {
                          <strong
                            className={classNames(
                              "plasmic_default__all",
                              "plasmic_default__strong",
                              "plasmic_default__strong__4WZ4j",
                              "__wab_text",
                              "plasmic_default__inline",
                              "DashboardNative__strong__mVfua"
                            )}
                          >
                            {"3"}
                          </strong>
                        }
                        <React.Fragment>
                          {" pontos dispon\u00edveis"}
                        </React.Fragment>
                      </React.Fragment>
                    </span>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "DashboardNative__freeBox__pd5Vh"
                    )}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span__xq7VZ"
                      )}
                    >
                      {"EXPERI\u00caNCIA"}
                    </span>
                    <strong
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__strong",
                        "plasmic_default__strong__4WZ4j",
                        "__wab_text",
                        "DashboardNative__strong__apquB"
                      )}
                    >
                      {"135 / 200 XP"}
                    </strong>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "DashboardNative__freeBox__izuY"
                    )}
                  >
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "DashboardNative__freeBox__rOocE"
                      )}
                    />
                  </div>
                  <p
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__p",
                      "plasmic_default__p__4WZ4j",
                      "__wab_text",
                      "DashboardNative__p__nEoE4"
                    )}
                  >
                    {"Mais 65 XP para sua pr\u00f3xima conquista."}
                  </p>
                </section>
                <section
                  className={classNames(
                    "plasmic_default__all",
                    "DashboardNative__section__kyZdO"
                  )}
                >
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "DashboardNative__freeBox__c5UBq"
                    )}
                  >
                    <h2
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__h2",
                        "plasmic_default__h2__4WZ4j",
                        "__wab_text",
                        "DashboardNative__h2__lVkma"
                      )}
                    >
                      {"di\u00e1rio de miss\u00f5es"}
                    </h2>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span__vdNxt"
                      )}
                    >
                      {"02"}
                    </span>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "DashboardNative__freeBox__oXv9W"
                    )}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span__nlbmL"
                      )}
                    >
                      {"PEQUENOS PASSOS, PROGRESSO REAL"}
                    </span>
                  </div>
                  <h2
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__h2",
                      "plasmic_default__h2__4WZ4j",
                      "__wab_text",
                      "DashboardNative__h2__nMyHb"
                    )}
                  >
                    {"O que vamos conquistar hoje?"}
                  </h2>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "DashboardNative__freeBox__liAjw"
                    )}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span__ii64S"
                      )}
                    >
                      {"Setembro 2026"}
                    </span>
                    <button
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__button",
                        "plasmic_default__button__4WZ4j",
                        "DashboardNative__button__mBoza"
                      )}
                      type={"button"}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "DashboardNative__span__aArEc"
                        )}
                      >
                        {"+ Nova miss\u00e3o"}
                      </span>
                    </button>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "DashboardNative__freeBox__buYu"
                    )}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span__llYr"
                      )}
                    >
                      {"SEG 14"}
                    </span>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span__pfu4J"
                      )}
                    >
                      {"TER 15"}
                    </span>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span__uxSyJ"
                      )}
                    >
                      {"QUA 16"}
                    </span>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span__er4Mm"
                      )}
                    >
                      {"QUI 17"}
                    </span>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span___6KnZi"
                      )}
                    >
                      {"SEX 18"}
                    </span>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span___3Z2YF"
                      )}
                    >
                      {"S\u00c1B 19"}
                    </span>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span__sT2Em"
                      )}
                    >
                      {"DOM 20"}
                    </span>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "DashboardNative__freeBox__k4PgY"
                    )}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span__xzYnC"
                      )}
                    >
                      {"Pendentes 3"}
                    </span>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "DashboardNative__span__kl5N1"
                      )}
                    >
                      {"Conclu\u00eddas 1"}
                    </span>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "DashboardNative__freeBox__qVp4R"
                    )}
                  >
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "DashboardNative__freeBox__fJaNe"
                      )}
                    >
                      <strong
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__strong",
                          "plasmic_default__strong__4WZ4j",
                          "__wab_text",
                          "DashboardNative__strong__i5DL"
                        )}
                      >
                        {"Mover o corpo por 30 minutos"}
                      </strong>
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "DashboardNative__span__s9Loa"
                        )}
                      >
                        {"Uma caminhada tamb\u00e9m \u00e9 uma conquista."}
                      </span>
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "DashboardNative__span__knyCt"
                        )}
                      >
                        {"M\u00e9dia \u00b7 +25 XP \u00b7 +15 moedas"}
                      </span>
                    </div>
                    <button
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__button",
                        "plasmic_default__button__4WZ4j",
                        "DashboardNative__button__bclvT"
                      )}
                      type={"button"}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "DashboardNative__span__bLYk"
                        )}
                      >
                        {"Concluir"}
                      </span>
                    </button>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "DashboardNative__freeBox___4BwK9"
                    )}
                  >
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "DashboardNative__freeBox__syWus"
                      )}
                    >
                      <strong
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__strong",
                          "plasmic_default__strong__4WZ4j",
                          "__wab_text",
                          "DashboardNative__strong__qsBf5"
                        )}
                      >
                        {"Ler 10 p\u00e1ginas de um livro"}
                      </strong>
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "DashboardNative__span__lBvVg"
                        )}
                      >
                        {"Novas ideias, um cap\u00edtulo de cada vez."}
                      </span>
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "DashboardNative__span__csmYi"
                        )}
                      >
                        {"F\u00e1cil \u00b7 +10 XP \u00b7 +5 moedas"}
                      </span>
                    </div>
                    <button
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__button",
                        "plasmic_default__button__4WZ4j",
                        "DashboardNative__button__zlEhW"
                      )}
                      type={"button"}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "DashboardNative__span__isGfA"
                        )}
                      >
                        {"Concluir"}
                      </span>
                    </button>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "DashboardNative__freeBox__rirK1"
                    )}
                  >
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "DashboardNative__freeBox__vik6F"
                      )}
                    >
                      <strong
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__strong",
                          "plasmic_default__strong__4WZ4j",
                          "__wab_text",
                          "DashboardNative__strong__jW6Jc"
                        )}
                      >
                        {"Dar um passo no projeto pessoal"}
                      </strong>
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "DashboardNative__span__sDieq"
                        )}
                      >
                        {"Reserve um momento de foco, s\u00f3 seu."}
                      </span>
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "DashboardNative__span__epA8K"
                        )}
                      >
                        {"Dif\u00edcil \u00b7 +50 XP \u00b7 +30 moedas"}
                      </span>
                    </div>
                    <button
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__button",
                        "plasmic_default__button__4WZ4j",
                        "DashboardNative__button__aBlmz"
                      )}
                      type={"button"}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "DashboardNative__span__spOvb"
                        )}
                      >
                        {"Concluir"}
                      </span>
                    </button>
                  </div>
                  <p
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__p",
                      "plasmic_default__p__4WZ4j",
                      "__wab_text",
                      "DashboardNative__p__geKtm"
                    )}
                  >
                    {
                      "Consist\u00eancia \u00e9 seu superpoder. 85 XP dispon\u00edveis hoje."
                    }
                  </p>
                </section>
              </div>
              <div
                className={classNames(
                  "plasmic_default__all",
                  "DashboardNative__freeBox__doLae"
                )}
              >
                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "__wab_text",
                    "DashboardNative__span__s5Df"
                  )}
                >
                  {
                    "VIDA REAL. ESP\u00cdRITO DE AVENTURA. CONTINUE, MESMO QUE SEJA UM POUQUINHO."
                  }
                </span>
              </div>
            </main>
            <footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(
                "plasmic_default__all",
                "DashboardNative__footer___5VBwr"
              )}
            >
              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "__wab_text",
                  "DashboardNative__span__vhWb"
                )}
              >
                {"Kaizen \u00b7 Um passo de cada vez."}
              </span>
            </footer>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "nav", "main", "h1", "footer"],
  header: ["header", "nav"],
  nav: ["nav"],
  main: ["main", "h1"],
  h1: ["h1"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: "header";
  nav: "nav";
  main: "main";
  h1: "h1";
  footer: "footer";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDashboardNative__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDashboardNative__VariantsArgs;
    args?: PlasmicDashboardNative__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicDashboardNative__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicDashboardNative__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDashboardNative__ArgProps,
          internalVariantPropNames: PlasmicDashboardNative__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDashboardNative__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicDashboardNative";
  } else {
    func.displayName = `PlasmicDashboardNative.${nodeName}`;
  }
  return func;
}

export const PlasmicDashboardNative = Object.assign(
  // Top-level PlasmicDashboardNative renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    nav: makeNodeComponent("nav"),
    main: makeNodeComponent("main"),
    h1: makeNodeComponent("h1"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicDashboardNative
    internalVariantProps: PlasmicDashboardNative__VariantProps,
    internalArgProps: PlasmicDashboardNative__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/dashboard-native",
      pagePath: "/dashboard-native",
      params: {},
      query: {}
    })
  }
);

export const PlasmicDashboardNative__HeadOptions = {
  meta: [{ name: "twitter:card", content: "summary" }],

  links: []
} as Record<"meta" | "links", Array<Record<string, string>>>;

export default PlasmicDashboardNative;
/* prettier-ignore-end */
