/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4WZ4je7EqYHVjfVVU6jztT
// Component: 0RrN6SStEp_l

import * as React from "react";

import { useRouter, Link } from "@tanstack/react-router";
import type { LinkProps } from "@tanstack/react-router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";
import "../../plasmic/plasmic__default_style.css"; // plasmic-import: global/defaultcss

import "./plasmic.css"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/projectcss
import "./PlasmicCharacterEditable.css"; // plasmic-import: 0RrN6SStEp_l/css

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicCharacterEditable__VariantMembers = {};
export type PlasmicCharacterEditable__VariantsArgs = {};
type VariantPropType = keyof PlasmicCharacterEditable__VariantsArgs;
export const PlasmicCharacterEditable__VariantProps =
  new Array<VariantPropType>();

export type PlasmicCharacterEditable__ArgsType = {};
type ArgPropType = keyof PlasmicCharacterEditable__ArgsType;
export const PlasmicCharacterEditable__ArgProps = new Array<ArgPropType>();

export type PlasmicCharacterEditable__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<"header">;
  nav?: Flex__<"nav">;
  main?: Flex__<"main">;
  h1?: Flex__<"h1">;
  footer?: Flex__<"footer">;
};

export interface DefaultCharacterEditableProps {}

const $$ = {};

function useTanStackRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCharacterEditable__RenderFunc(props: {
  variants: PlasmicCharacterEditable__VariantsArgs;
  args: PlasmicCharacterEditable__ArgsType;
  overrides: PlasmicCharacterEditable__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __tanstackRouter = useTanStackRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "plasmic_default__all",
            "root_reset_4WZ4je7EqYHVjfVVU6jztT",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            "CharacterEditable__root__yynsF"
          )}
        >
          <div
            className={classNames(
              "plasmic_default__all",
              "CharacterEditable__freeBox__fXeK5"
            )}
          >
            <header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames(
                "plasmic_default__all",
                "CharacterEditable__header__ajdCs"
              )}
            >
              <strong
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__strong",
                  "plasmic_default__strong__4WZ4j",
                  "__wab_text",
                  "CharacterEditable__strong__c3PT"
                )}
              >
                {"kaizen"}
              </strong>
              <nav
                data-plasmic-name={"nav"}
                data-plasmic-override={overrides.nav}
                className={classNames(
                  "plasmic_default__all",
                  "CharacterEditable__nav__wctQl"
                )}
              >
                <PlasmicLink__
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__a",
                    "plasmic_default__a__4WZ4j",
                    "__wab_text",
                    "CharacterEditable__link__f9SOt"
                  )}
                  component={Link}
                  href={"/dashboard"}
                  platform={"tanstack"}
                >
                  {"Vis\u00e3o geral"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__a",
                    "plasmic_default__a__4WZ4j",
                    "__wab_text",
                    "CharacterEditable__link__pCxBl"
                  )}
                  component={Link}
                  href={"/tasks"}
                  platform={"tanstack"}
                >
                  {"Miss\u00f5es"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__a",
                    "plasmic_default__a__4WZ4j",
                    "__wab_text",
                    "CharacterEditable__link__jtn09"
                  )}
                  component={Link}
                  href={"/character"}
                  platform={"tanstack"}
                >
                  {"Personagem"}
                </PlasmicLink__>
              </nav>
              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "__wab_text",
                  "CharacterEditable__span__oxBkq"
                )}
              >
                {"EMBER \u03b1"}
              </span>
            </header>
            <main
              data-plasmic-name={"main"}
              data-plasmic-override={overrides.main}
              className={classNames(
                "plasmic_default__all",
                "CharacterEditable__main__jx8LQ"
              )}
            >
              <div
                className={classNames(
                  "plasmic_default__all",
                  "CharacterEditable__freeBox__rfZi4"
                )}
              >
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "CharacterEditable__freeBox__aqlTw"
                  )}
                >
                  <span
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__span",
                      "plasmic_default__span__4WZ4j",
                      "__wab_text",
                      "CharacterEditable__span__neXac"
                    )}
                  >
                    {"03 / SER"}
                  </span>
                </div>
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__h1",
                    "plasmic_default__h1__4WZ4j",
                    "__wab_text",
                    "CharacterEditable__h1___5CoCf"
                  )}
                >
                  {"Alex"}
                </h1>
                <p
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__p",
                    "plasmic_default__p__4WZ4j",
                    "__wab_text",
                    "CharacterEditable__p__bs1Q9"
                  )}
                >
                  {"N\u00edvel 2 \u00b7 135/200 XP"}
                </p>
              </div>
              <section
                className={classNames(
                  "plasmic_default__all",
                  "CharacterEditable__section___7WhKf"
                )}
              >
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "CharacterEditable__freeBox__byNS"
                  )}
                >
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "CharacterEditable__freeBox__kNckz"
                    )}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "CharacterEditable__span__rBmL1"
                      )}
                    >
                      {"\u2726"}
                    </span>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "CharacterEditable__freeBox__bXsgF"
                    )}
                  >
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "CharacterEditable__freeBox___7IuwM"
                      )}
                    >
                      <strong
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__strong",
                          "plasmic_default__strong__4WZ4j",
                          "__wab_text",
                          "CharacterEditable__strong__tLeD3"
                        )}
                      >
                        {"Progresso para o n\u00edvel 3"}
                      </strong>
                      <strong
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__strong",
                          "plasmic_default__strong__4WZ4j",
                          "__wab_text",
                          "CharacterEditable__strong__n8M5B"
                        )}
                      >
                        {"68%"}
                      </strong>
                    </div>
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "CharacterEditable__freeBox__c3Yr"
                      )}
                    >
                      <div
                        className={classNames(
                          "plasmic_default__all",
                          "CharacterEditable__freeBox__t2B4V"
                        )}
                      />
                    </div>
                    <p
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__p",
                        "plasmic_default__p__4WZ4j",
                        "__wab_text",
                        "CharacterEditable__p__cdtyO"
                      )}
                    >
                      {"Faltam 65 XP para a pr\u00f3xima conquista."}
                    </p>
                  </div>
                </div>
              </section>
              <section
                className={classNames(
                  "plasmic_default__all",
                  "CharacterEditable__section__bZa4"
                )}
              >
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "CharacterEditable__freeBox__oLzfM"
                  )}
                >
                  <h2
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__h2",
                      "plasmic_default__h2__4WZ4j",
                      "__wab_text",
                      "CharacterEditable__h2__kiDDm"
                    )}
                  >
                    {"Atributos"}
                  </h2>
                  <span
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__span",
                      "plasmic_default__span__4WZ4j",
                      "__wab_text",
                      "CharacterEditable__span__rLwO"
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>
                        {"Pontos dispon\u00edveis: "}
                      </React.Fragment>
                      {
                        <strong
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__strong",
                            "plasmic_default__strong__4WZ4j",
                            "__wab_text",
                            "plasmic_default__inline",
                            "CharacterEditable__strong__dTtKl"
                          )}
                        >
                          {"3"}
                        </strong>
                      }
                      <React.Fragment>{""}</React.Fragment>
                    </React.Fragment>
                  </span>
                </div>
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "CharacterEditable__freeBox__umcuB"
                  )}
                >
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "CharacterEditable__freeBox__aelk0"
                    )}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "CharacterEditable__span__hddqC"
                      )}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "CharacterEditable__span__t34Yi"
                        )}
                      >
                        {"\u2726"}
                      </span>
                    </span>
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "CharacterEditable__freeBox__yt3Ot"
                      )}
                    >
                      <strong
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__strong",
                          "plasmic_default__strong__4WZ4j",
                          "__wab_text",
                          "CharacterEditable__strong__i7MlV"
                        )}
                      >
                        {"For\u00e7a"}
                      </strong>
                      <div
                        className={classNames(
                          "plasmic_default__all",
                          "CharacterEditable__freeBox__qE54X"
                        )}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "CharacterEditable__span__hlms7"
                          )}
                        >
                          {
                            "Resist\u00eancia f\u00edsica e determina\u00e7\u00e3o"
                          }
                        </span>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "CharacterEditable__freeBox__y4KH"
                    )}
                  >
                    <strong
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__strong",
                        "plasmic_default__strong__4WZ4j",
                        "__wab_text",
                        "CharacterEditable__strong__iaGwg"
                      )}
                    >
                      {"05"}
                    </strong>
                    <button
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__button",
                        "plasmic_default__button__4WZ4j",
                        "CharacterEditable__button__ouWLs"
                      )}
                      type={"button"}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "CharacterEditable__span__sCIfm"
                        )}
                      >
                        {"+1"}
                      </span>
                    </button>
                  </div>
                </div>
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "CharacterEditable__freeBox__a1UZt"
                  )}
                >
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "CharacterEditable__freeBox__oH0Uw"
                    )}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "CharacterEditable__span__n7Sn"
                      )}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "CharacterEditable__span__kbRAe"
                        )}
                      >
                        {"\u2726"}
                      </span>
                    </span>
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "CharacterEditable__freeBox__edfRh"
                      )}
                    >
                      <strong
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__strong",
                          "plasmic_default__strong__4WZ4j",
                          "__wab_text",
                          "CharacterEditable__strong__i6Nqg"
                        )}
                      >
                        {"Intelig\u00eancia"}
                      </strong>
                      <div
                        className={classNames(
                          "plasmic_default__all",
                          "CharacterEditable__freeBox__hdSpG"
                        )}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "CharacterEditable__span__mn4Et"
                          )}
                        >
                          {"Aprendizado e racioc\u00ednio"}
                        </span>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "CharacterEditable__freeBox__dGmXy"
                    )}
                  >
                    <strong
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__strong",
                        "plasmic_default__strong__4WZ4j",
                        "__wab_text",
                        "CharacterEditable__strong__r31Mp"
                      )}
                    >
                      {"07"}
                    </strong>
                    <button
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__button",
                        "plasmic_default__button__4WZ4j",
                        "CharacterEditable__button___5W4EL"
                      )}
                      type={"button"}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "CharacterEditable__span__nQrzD"
                        )}
                      >
                        {"+1"}
                      </span>
                    </button>
                  </div>
                </div>
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "CharacterEditable__freeBox__jcAHq"
                  )}
                >
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "CharacterEditable__freeBox__yELeV"
                    )}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "CharacterEditable__span__qM4M3"
                      )}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "CharacterEditable__span___31B4G"
                        )}
                      >
                        {"\u2726"}
                      </span>
                    </span>
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "CharacterEditable__freeBox__hm04V"
                      )}
                    >
                      <strong
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__strong",
                          "plasmic_default__strong__4WZ4j",
                          "__wab_text",
                          "CharacterEditable__strong__bJy7Z"
                        )}
                      >
                        {"Disciplina"}
                      </strong>
                      <div
                        className={classNames(
                          "plasmic_default__all",
                          "CharacterEditable__freeBox__xZqjZ"
                        )}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "CharacterEditable__span__wgHl5"
                          )}
                        >
                          {"Foco e consist\u00eancia"}
                        </span>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "CharacterEditable__freeBox___7A6Ne"
                    )}
                  >
                    <strong
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__strong",
                        "plasmic_default__strong__4WZ4j",
                        "__wab_text",
                        "CharacterEditable__strong__l7VSf"
                      )}
                    >
                      {"06"}
                    </strong>
                    <button
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__button",
                        "plasmic_default__button__4WZ4j",
                        "CharacterEditable__button__iYp1Q"
                      )}
                      type={"button"}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "CharacterEditable__span__bv3Ox"
                        )}
                      >
                        {"+1"}
                      </span>
                    </button>
                  </div>
                </div>
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "CharacterEditable__freeBox__eZh9M"
                  )}
                >
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "CharacterEditable__freeBox__nrwLq"
                    )}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "CharacterEditable__span__pbLtw"
                      )}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "CharacterEditable__span__lsgbK"
                        )}
                      >
                        {"\u2726"}
                      </span>
                    </span>
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "CharacterEditable__freeBox__yRxgb"
                      )}
                    >
                      <strong
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__strong",
                          "plasmic_default__strong__4WZ4j",
                          "__wab_text",
                          "CharacterEditable__strong__pALtw"
                        )}
                      >
                        {"Criatividade"}
                      </strong>
                      <div
                        className={classNames(
                          "plasmic_default__all",
                          "CharacterEditable__freeBox__hLYp"
                        )}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "CharacterEditable__span__rbiEm"
                          )}
                        >
                          {
                            "Inova\u00e7\u00e3o e resolu\u00e7\u00e3o de problemas"
                          }
                        </span>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "CharacterEditable__freeBox__obE7Z"
                    )}
                  >
                    <strong
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__strong",
                        "plasmic_default__strong__4WZ4j",
                        "__wab_text",
                        "CharacterEditable__strong__nt0K"
                      )}
                    >
                      {"04"}
                    </strong>
                    <button
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__button",
                        "plasmic_default__button__4WZ4j",
                        "CharacterEditable__button___5Oyu8"
                      )}
                      type={"button"}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "CharacterEditable__span__qFqcm"
                        )}
                      >
                        {"+1"}
                      </span>
                    </button>
                  </div>
                </div>
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "CharacterEditable__freeBox__zVdHi"
                  )}
                >
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "CharacterEditable__freeBox__ng48Q"
                    )}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "CharacterEditable__span__kbeq2"
                      )}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "CharacterEditable__span__gsb9S"
                        )}
                      >
                        {"\u2726"}
                      </span>
                    </span>
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "CharacterEditable__freeBox__mfIh5"
                      )}
                    >
                      <strong
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__strong",
                          "plasmic_default__strong__4WZ4j",
                          "__wab_text",
                          "CharacterEditable__strong__eDs9U"
                        )}
                      >
                        {"Resili\u00eancia"}
                      </strong>
                      <div
                        className={classNames(
                          "plasmic_default__all",
                          "CharacterEditable__freeBox__oQUuZ"
                        )}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "CharacterEditable__span__mmZgE"
                          )}
                        >
                          {"Capacidade de superar obst\u00e1culos"}
                        </span>
                      </div>
                    </div>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "CharacterEditable__freeBox__vZuot"
                    )}
                  >
                    <strong
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__strong",
                        "plasmic_default__strong__4WZ4j",
                        "__wab_text",
                        "CharacterEditable__strong___7WRq"
                      )}
                    >
                      {"05"}
                    </strong>
                    <button
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__button",
                        "plasmic_default__button__4WZ4j",
                        "CharacterEditable__button__yy05X"
                      )}
                      type={"button"}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "CharacterEditable__span__igd6D"
                        )}
                      >
                        {"+1"}
                      </span>
                    </button>
                  </div>
                </div>
              </section>
              <section
                className={classNames(
                  "plasmic_default__all",
                  "CharacterEditable__section__elDvQ"
                )}
              >
                <h2
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__h2",
                    "plasmic_default__h2__4WZ4j",
                    "__wab_text",
                    "CharacterEditable__h2__lA9S"
                  )}
                >
                  {"Sua jornada"}
                </h2>
                <p
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__p",
                    "plasmic_default__p__4WZ4j",
                    "__wab_text",
                    "CharacterEditable__p__bF4Bf"
                  )}
                >
                  {"Uma miss\u00e3o de cada vez. Cada pequena conquista conta."}
                </p>
              </section>
            </main>
            <footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(
                "plasmic_default__all",
                "CharacterEditable__footer___2HwhM"
              )}
            >
              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "__wab_text",
                  "CharacterEditable__span__oFZhT"
                )}
              >
                {"Kaizen \u00b7 Um passo de cada vez."}
              </span>
            </footer>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "nav", "main", "h1", "footer"],
  header: ["header", "nav"],
  nav: ["nav"],
  main: ["main", "h1"],
  h1: ["h1"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: "header";
  nav: "nav";
  main: "main";
  h1: "h1";
  footer: "footer";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCharacterEditable__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCharacterEditable__VariantsArgs;
    args?: PlasmicCharacterEditable__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicCharacterEditable__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicCharacterEditable__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCharacterEditable__ArgProps,
          internalVariantPropNames: PlasmicCharacterEditable__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCharacterEditable__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCharacterEditable";
  } else {
    func.displayName = `PlasmicCharacterEditable.${nodeName}`;
  }
  return func;
}

export const PlasmicCharacterEditable = Object.assign(
  // Top-level PlasmicCharacterEditable renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    nav: makeNodeComponent("nav"),
    main: makeNodeComponent("main"),
    h1: makeNodeComponent("h1"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicCharacterEditable
    internalVariantProps: PlasmicCharacterEditable__VariantProps,
    internalArgProps: PlasmicCharacterEditable__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/character-editable",
      pagePath: "/character-editable",
      params: {},
      query: {}
    })
  }
);

export const PlasmicCharacterEditable__HeadOptions = {
  meta: [{ name: "twitter:card", content: "summary" }],

  links: []
} as Record<"meta" | "links", Array<Record<string, string>>>;

export default PlasmicCharacterEditable;
/* prettier-ignore-end */
