/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4WZ4je7EqYHVjfVVU6jztT
// Component: tXrDjy_KeWj9

import * as React from "react";

import { useRouter, Link } from "@tanstack/react-router";
import type { LinkProps } from "@tanstack/react-router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";
import "../../plasmic/plasmic__default_style.css"; // plasmic-import: global/defaultcss

import "./plasmic.css"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/projectcss
import "./PlasmicMissionsEditable.css"; // plasmic-import: tXrDjy_KeWj9/css

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicMissionsEditable__VariantMembers = {};
export type PlasmicMissionsEditable__VariantsArgs = {};
type VariantPropType = keyof PlasmicMissionsEditable__VariantsArgs;
export const PlasmicMissionsEditable__VariantProps =
  new Array<VariantPropType>();

export type PlasmicMissionsEditable__ArgsType = {};
type ArgPropType = keyof PlasmicMissionsEditable__ArgsType;
export const PlasmicMissionsEditable__ArgProps = new Array<ArgPropType>();

export type PlasmicMissionsEditable__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<"header">;
  nav?: Flex__<"nav">;
  main?: Flex__<"main">;
  h1?: Flex__<"h1">;
  textbox?: Flex__<"input">;
  textarea?: Flex__<"textarea">;
  textbox2?: Flex__<"input">;
  footer?: Flex__<"footer">;
};

export interface DefaultMissionsEditableProps {}

const $$ = {};

function useTanStackRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicMissionsEditable__RenderFunc(props: {
  variants: PlasmicMissionsEditable__VariantsArgs;
  args: PlasmicMissionsEditable__ArgsType;
  overrides: PlasmicMissionsEditable__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __tanstackRouter = useTanStackRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "textbox.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "textarea.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "textbox2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "plasmic_default__all",
            "root_reset_4WZ4je7EqYHVjfVVU6jztT",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            "MissionsEditable__root__jf4K3"
          )}
        >
          <div
            className={classNames(
              "plasmic_default__all",
              "MissionsEditable__freeBox___9LSlh"
            )}
          >
            <header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames(
                "plasmic_default__all",
                "MissionsEditable__header__qwfzO"
              )}
            >
              <strong
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__strong",
                  "plasmic_default__strong__4WZ4j",
                  "__wab_text",
                  "MissionsEditable__strong__nyuDp"
                )}
              >
                {"kaizen"}
              </strong>
              <nav
                data-plasmic-name={"nav"}
                data-plasmic-override={overrides.nav}
                className={classNames(
                  "plasmic_default__all",
                  "MissionsEditable__nav__ep3Uf"
                )}
              >
                <PlasmicLink__
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__a",
                    "plasmic_default__a__4WZ4j",
                    "__wab_text",
                    "MissionsEditable__link__p526Z"
                  )}
                  component={Link}
                  href={"/dashboard"}
                  platform={"tanstack"}
                >
                  {"Vis\u00e3o geral"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__a",
                    "plasmic_default__a__4WZ4j",
                    "__wab_text",
                    "MissionsEditable__link__aEtMg"
                  )}
                  component={Link}
                  href={"/tasks"}
                  platform={"tanstack"}
                >
                  {"Miss\u00f5es"}
                </PlasmicLink__>
                <PlasmicLink__
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__a",
                    "plasmic_default__a__4WZ4j",
                    "__wab_text",
                    "MissionsEditable__link__x7G3R"
                  )}
                  component={Link}
                  href={"/character"}
                  platform={"tanstack"}
                >
                  {"Personagem"}
                </PlasmicLink__>
              </nav>
              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "__wab_text",
                  "MissionsEditable__span__qAqXg"
                )}
              >
                {"EMBER \u03b1"}
              </span>
            </header>
            <main
              data-plasmic-name={"main"}
              data-plasmic-override={overrides.main}
              className={classNames(
                "plasmic_default__all",
                "MissionsEditable__main__l0DhO"
              )}
            >
              <div
                className={classNames(
                  "plasmic_default__all",
                  "MissionsEditable__freeBox__mvZq3"
                )}
              >
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "MissionsEditable__freeBox__nyovn"
                  )}
                >
                  <span
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__span",
                      "plasmic_default__span__4WZ4j",
                      "__wab_text",
                      "MissionsEditable__span__hLw1I"
                    )}
                  >
                    {"02 / FAZER"}
                  </span>
                </div>
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "MissionsEditable__freeBox__sJoDm"
                  )}
                >
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "MissionsEditable__freeBox__q1Rlw"
                    )}
                  >
                    <h1
                      data-plasmic-name={"h1"}
                      data-plasmic-override={overrides.h1}
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__h1",
                        "plasmic_default__h1__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__h1__edzDb"
                      )}
                    >
                      {"Miss\u00f5es"}
                    </h1>
                    <p
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__p",
                        "plasmic_default__p__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__p__kYh4"
                      )}
                    >
                      {"Crie e complete miss\u00f5es para evoluir."}
                    </p>
                  </div>
                  <button
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__button",
                      "plasmic_default__button__4WZ4j",
                      "MissionsEditable__button__p5M5"
                    )}
                    type={"button"}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__span__wrQIx"
                      )}
                    >
                      {"+ Nova miss\u00e3o"}
                    </span>
                  </button>
                </div>
              </div>
              <section
                className={classNames(
                  "plasmic_default__all",
                  "MissionsEditable__section__eDh6"
                )}
              >
                <h2
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__h2",
                    "plasmic_default__h2__4WZ4j",
                    "__wab_text",
                    "MissionsEditable__h2__rf6Nq"
                  )}
                >
                  {"Pendentes"}
                </h2>
                <p
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__p",
                    "plasmic_default__p__4WZ4j",
                    "__wab_text",
                    "MissionsEditable__p___5BuOg"
                  )}
                >
                  {"Pequenos passos, progresso real."}
                </p>
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "MissionsEditable__freeBox__bwbSv"
                  )}
                >
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "MissionsEditable__freeBox__jtCyx"
                    )}
                  >
                    <strong
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__strong",
                        "plasmic_default__strong__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__strong__wcuT0"
                      )}
                    >
                      {"Mover o corpo por 30 minutos"}
                    </strong>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__span___8IE7T"
                      )}
                    >
                      {"Uma caminhada tamb\u00e9m \u00e9 uma conquista."}
                    </span>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__span__mljYf"
                      )}
                    >
                      {"M\u00e9dia \u00b7 +25 XP \u00b7 +15 moedas"}
                    </span>
                  </div>
                  <button
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__button",
                      "plasmic_default__button__4WZ4j",
                      "MissionsEditable__button__ynWnj"
                    )}
                    type={"button"}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__span__tHp6D"
                      )}
                    >
                      {"Concluir"}
                    </span>
                  </button>
                </div>
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "MissionsEditable__freeBox___7EYhB"
                  )}
                >
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "MissionsEditable__freeBox___2WwCw"
                    )}
                  >
                    <strong
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__strong",
                        "plasmic_default__strong__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__strong__q78Ln"
                      )}
                    >
                      {"Ler 10 p\u00e1ginas de um livro"}
                    </strong>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__span__uPiEf"
                      )}
                    >
                      {"Novas ideias, um cap\u00edtulo de cada vez."}
                    </span>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__span__soHtf"
                      )}
                    >
                      {"F\u00e1cil \u00b7 +10 XP \u00b7 +5 moedas"}
                    </span>
                  </div>
                  <button
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__button",
                      "plasmic_default__button__4WZ4j",
                      "MissionsEditable__button__rggTy"
                    )}
                    type={"button"}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__span__rzwNp"
                      )}
                    >
                      {"Concluir"}
                    </span>
                  </button>
                </div>
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "MissionsEditable__freeBox__dFfs1"
                  )}
                >
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "MissionsEditable__freeBox__zLk9"
                    )}
                  >
                    <strong
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__strong",
                        "plasmic_default__strong__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__strong__a9Ken"
                      )}
                    >
                      {"Dar um passo no projeto pessoal"}
                    </strong>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__span__ngcy2"
                      )}
                    >
                      {"Reserve um momento de foco, s\u00f3 seu."}
                    </span>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__span__sz0Lg"
                      )}
                    >
                      {"Dif\u00edcil \u00b7 +50 XP \u00b7 +30 moedas"}
                    </span>
                  </div>
                  <button
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__button",
                      "plasmic_default__button__4WZ4j",
                      "MissionsEditable__button__zquTq"
                    )}
                    type={"button"}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__span__bribn"
                      )}
                    >
                      {"Concluir"}
                    </span>
                  </button>
                </div>
              </section>
              <section
                className={classNames(
                  "plasmic_default__all",
                  "MissionsEditable__section___7AbZx"
                )}
              >
                <h2
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__h2",
                    "plasmic_default__h2__4WZ4j",
                    "__wab_text",
                    "MissionsEditable__h2__btjOz"
                  )}
                >
                  {"Conclu\u00eddas"}
                </h2>
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "MissionsEditable__freeBox__lFhXg"
                  )}
                >
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "MissionsEditable__freeBox__zlD7T"
                    )}
                  >
                    <strong
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__strong",
                        "plasmic_default__strong__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__strong__eyeOw"
                      )}
                    >
                      {"Ler e refletir por 15 minutos"}
                    </strong>
                    <p
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__p",
                        "plasmic_default__p__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__p__ez4Bx"
                      )}
                    >
                      {"Mais uma conquista na jornada."}
                    </p>
                  </div>
                  <span
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__span",
                      "plasmic_default__span__4WZ4j",
                      "__wab_text",
                      "MissionsEditable__span__ybzA8"
                    )}
                  >
                    {"\u2713 Conclu\u00edda"}
                  </span>
                </div>
              </section>
              <section
                className={classNames(
                  "plasmic_default__all",
                  "MissionsEditable__section__ipLOh"
                )}
              >
                <h2
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__h2",
                    "plasmic_default__h2__4WZ4j",
                    "__wab_text",
                    "MissionsEditable__h2___3IAlV"
                  )}
                >
                  {"Criar nova miss\u00e3o"}
                </h2>
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "MissionsEditable__freeBox__cpi1F"
                  )}
                >
                  <label
                    className={classNames(
                      "plasmic_default__all",
                      "MissionsEditable__label___3RXe6"
                    )}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__span__qusQi"
                      )}
                    >
                      {"T\u00edtulo"}
                    </span>
                    <input
                      data-plasmic-name={"textbox"}
                      data-plasmic-override={overrides.textbox}
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__input",
                        "plasmic_default__input__4WZ4j",
                        "MissionsEditable__textbox__gDMs"
                      )}
                      onChange={async (...eventArgs: any) => {
                        (e => {
                          generateStateOnChangeProp($state, [
                            "textbox",
                            "value"
                          ])(e.target.value);
                        }).apply(null, eventArgs);
                      }}
                      placeholder={"Ex: Ler 20 p\u00e1ginas"}
                      ref={ref => {
                        $refs["textbox"] = ref;
                      }}
                      value={
                        generateStateValueProp($state, ["textbox", "value"]) ??
                        ""
                      }
                    />
                  </label>
                  <label
                    className={classNames(
                      "plasmic_default__all",
                      "MissionsEditable__label__kQ"
                    )}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__span___38JIj"
                      )}
                    >
                      {"Descri\u00e7\u00e3o"}
                    </span>
                    <textarea
                      data-plasmic-name={"textarea"}
                      data-plasmic-override={overrides.textarea}
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__textarea",
                        "plasmic_default__textarea__4WZ4j",
                        "MissionsEditable__textarea__xu2Gj"
                      )}
                      onChange={async (...eventArgs: any) => {
                        (e => {
                          generateStateOnChangeProp($state, [
                            "textarea",
                            "value"
                          ])(e.target.value);
                        }).apply(null, eventArgs);
                      }}
                      placeholder={"Detalhes da miss\u00e3o (opcional)"}
                      ref={ref => {
                        $refs["textarea"] = ref;
                      }}
                      value={
                        generateStateValueProp($state, ["textarea", "value"]) ??
                        ""
                      }
                    />
                  </label>
                  <label
                    className={classNames(
                      "plasmic_default__all",
                      "MissionsEditable__label__bVubI"
                    )}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__span__uVdxo"
                      )}
                    >
                      {"Dificuldade"}
                    </span>
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "MissionsEditable__freeBox__qMZlE"
                      )}
                    >
                      <div
                        className={classNames(
                          "plasmic_default__all",
                          "MissionsEditable__freeBox__cK3J1"
                        )}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "MissionsEditable__span__sNVmX"
                          )}
                        >
                          {"F\u00e1cil (+10 XP)"}
                        </span>
                      </div>
                      <div
                        className={classNames(
                          "plasmic_default__all",
                          "MissionsEditable__freeBox___4Njht"
                        )}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "MissionsEditable__span__yuWbl"
                          )}
                        >
                          {"M\u00e9dio (+25 XP)"}
                        </span>
                      </div>
                      <div
                        className={classNames(
                          "plasmic_default__all",
                          "MissionsEditable__freeBox___7L9GR"
                        )}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "MissionsEditable__span___1LwQc"
                          )}
                        >
                          {"Dif\u00edcil (+50 XP)"}
                        </span>
                      </div>
                      <div
                        className={classNames(
                          "plasmic_default__all",
                          "MissionsEditable__freeBox__oikKw"
                        )}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "MissionsEditable__span__etbig"
                          )}
                        >
                          {"\u00c9pico (+100 XP)"}
                        </span>
                      </div>
                    </div>
                  </label>
                  <label
                    className={classNames(
                      "plasmic_default__all",
                      "MissionsEditable__label__cM4TC"
                    )}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__span__vshmu"
                      )}
                    >
                      {"Data de vencimento"}
                    </span>
                    <input
                      data-plasmic-name={"textbox2"}
                      data-plasmic-override={overrides.textbox2}
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__input",
                        "plasmic_default__input__4WZ4j",
                        "MissionsEditable__textbox2__z0Rly"
                      )}
                      onChange={async (...eventArgs: any) => {
                        (e => {
                          generateStateOnChangeProp($state, [
                            "textbox2",
                            "value"
                          ])(e.target.value);
                        }).apply(null, eventArgs);
                      }}
                      ref={ref => {
                        $refs["textbox2"] = ref;
                      }}
                      type={"date"}
                      value={
                        generateStateValueProp($state, ["textbox2", "value"]) ??
                        ""
                      }
                    />
                  </label>
                  <button
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__button",
                      "plasmic_default__button__4WZ4j",
                      "MissionsEditable__button__z1X6W"
                    )}
                    type={"button"}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "MissionsEditable__span__dIyim"
                      )}
                    >
                      {"Criar miss\u00e3o"}
                    </span>
                  </button>
                </div>
              </section>
            </main>
            <footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(
                "plasmic_default__all",
                "MissionsEditable__footer__tf1Rz"
              )}
            >
              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "__wab_text",
                  "MissionsEditable__span__g4KPz"
                )}
              >
                {"Kaizen \u00b7 Um passo de cada vez."}
              </span>
            </footer>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "nav",
    "main",
    "h1",
    "textbox",
    "textarea",
    "textbox2",
    "footer"
  ],
  header: ["header", "nav"],
  nav: ["nav"],
  main: ["main", "h1", "textbox", "textarea", "textbox2"],
  h1: ["h1"],
  textbox: ["textbox"],
  textarea: ["textarea"],
  textbox2: ["textbox2"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: "header";
  nav: "nav";
  main: "main";
  h1: "h1";
  textbox: "input";
  textarea: "textarea";
  textbox2: "input";
  footer: "footer";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMissionsEditable__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicMissionsEditable__VariantsArgs;
    args?: PlasmicMissionsEditable__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicMissionsEditable__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicMissionsEditable__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMissionsEditable__ArgProps,
          internalVariantPropNames: PlasmicMissionsEditable__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMissionsEditable__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMissionsEditable";
  } else {
    func.displayName = `PlasmicMissionsEditable.${nodeName}`;
  }
  return func;
}

export const PlasmicMissionsEditable = Object.assign(
  // Top-level PlasmicMissionsEditable renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    nav: makeNodeComponent("nav"),
    main: makeNodeComponent("main"),
    h1: makeNodeComponent("h1"),
    textbox: makeNodeComponent("textbox"),
    textarea: makeNodeComponent("textarea"),
    textbox2: makeNodeComponent("textbox2"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicMissionsEditable
    internalVariantProps: PlasmicMissionsEditable__VariantProps,
    internalArgProps: PlasmicMissionsEditable__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/missions-editable",
      pagePath: "/missions-editable",
      params: {},
      query: {}
    })
  }
);

export const PlasmicMissionsEditable__HeadOptions = {
  meta: [{ name: "twitter:card", content: "summary" }],

  links: []
} as Record<"meta" | "links", Array<Record<string, string>>>;

export default PlasmicMissionsEditable;
/* prettier-ignore-end */
