/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4WZ4je7EqYHVjfVVU6jztT
// Component: dFjf30lVXEDp

import * as React from "react";

import { useRouter, Link } from "@tanstack/react-router";
import type { LinkProps } from "@tanstack/react-router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { BaseButton } from "@plasmicpkgs/react-aria/skinny/registerButton";
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";
import "../../plasmic/plasmic__default_style.css"; // plasmic-import: global/defaultcss

import "./plasmic.css"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/projectcss
import "./PlasmicButton.css"; // plasmic-import: dFjf30lVXEDp/css

import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: C-P9ABkVrUnR/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: iE72O1j37xqm/icon

createPlasmicElementProxy;

export type PlasmicButton__VariantMembers = {
  color: "neutral" | "muted" | "success" | "warning" | "errorDestructive";
  type: "soft" | "bordered";
  size: "extraSmall" | "small" | "large" | "extraLarge";
  iconStart: "iconStart";
  iconEnd: "iconEnd";
  roundedFull: "roundedFull";
  flatSide: "top" | "right" | "bottom" | "left";
};
export type PlasmicButton__VariantsArgs = {
  color?: SingleChoiceArg<
    "neutral" | "muted" | "success" | "warning" | "errorDestructive"
  >;
  type?: SingleChoiceArg<"soft" | "bordered">;
  size?: SingleChoiceArg<"extraSmall" | "small" | "large" | "extraLarge">;
  iconStart?: SingleBooleanChoiceArg<"iconStart">;
  iconEnd?: SingleBooleanChoiceArg<"iconEnd">;
  roundedFull?: SingleBooleanChoiceArg<"roundedFull">;
  flatSide?: MultiChoiceArg<"top" | "right" | "bottom" | "left">;
};
type VariantPropType = keyof PlasmicButton__VariantsArgs;
export const PlasmicButton__VariantProps = new Array<VariantPropType>(
  "color",
  "type",
  "size",
  "iconStart",
  "iconEnd",
  "roundedFull",
  "flatSide"
);

export type PlasmicButton__ArgsType = {
  disabled?: boolean;
  submitsForm?: boolean;
  resetsForm?: boolean;
  ariaLabel?: string;
  onClick?: (event: any) => void;
  linkTo?: string;
  openLinkInNewTab?: boolean;
  start?: React.ReactNode;
  label?: React.ReactNode;
  end?: React.ReactNode;
};
type ArgPropType = keyof PlasmicButton__ArgsType;
export const PlasmicButton__ArgProps = new Array<ArgPropType>(
  "disabled",
  "submitsForm",
  "resetsForm",
  "ariaLabel",
  "onClick",
  "linkTo",
  "openLinkInNewTab",
  "start",
  "label",
  "end"
);

export type PlasmicButton__OverridesType = {
  root?: Flex__<typeof BaseButton>;
  softBackground?: Flex__<"div">;
  border?: Flex__<"div">;
  interactionEffect?: Flex__<"div">;
};

export interface DefaultButtonProps {
  disabled?: boolean;
  submitsForm?: boolean;
  resetsForm?: boolean;
  ariaLabel?: string;
  onClick?: (event: any) => void;
  linkTo?: string;
  openLinkInNewTab?: boolean;
  start?: React.ReactNode;
  label?: React.ReactNode;
  end?: React.ReactNode;
  color?: SingleChoiceArg<
    "neutral" | "muted" | "success" | "warning" | "errorDestructive"
  >;
  type?: SingleChoiceArg<"soft" | "bordered">;
  size?: SingleChoiceArg<"extraSmall" | "small" | "large" | "extraLarge">;
  iconStart?: SingleBooleanChoiceArg<"iconStart">;
  iconEnd?: SingleBooleanChoiceArg<"iconEnd">;
  roundedFull?: SingleBooleanChoiceArg<"roundedFull">;
  flatSide?: MultiChoiceArg<"top" | "right" | "bottom" | "left">;
  className?: string;
}

const $$ = {};

function useTanStackRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicButton__RenderFunc(props: {
  variants: PlasmicButton__VariantsArgs;
  args: PlasmicButton__ArgsType;
  overrides: PlasmicButton__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          linkTo: "",
          openLinkInNewTab: false
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __tanstackRouter = useTanStackRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "color",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.color
      },
      {
        path: "size",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.size
      },
      {
        path: "iconStart",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.iconStart
      },
      {
        path: "iconEnd",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.iconEnd
      },
      {
        path: "roundedFull",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.roundedFull
      },
      {
        path: "type",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.type
      },
      {
        path: "flatSide",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => $props.flatSide
      }
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  const [$ccVariants, setDollarCcVariants] = React.useState<
    Record<string, boolean>
  >({
    hovered: false,
    pressed: false,
    focused: false,
    focusVisible: false,
    disabled: false
  });
  const updateVariant = React.useCallback(
    (changes: Record<string, boolean>) => {
      setDollarCcVariants(prev => {
        if (!Object.keys(changes).some(k => prev[k] !== changes[k])) {
          return prev;
        }
        return { ...prev, ...changes };
      });
    },
    []
  );

  return (
    <BaseButton
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      aria-label={args.ariaLabel}
      className={classNames(
        "__wab_instance",
        "root_reset_4WZ4je7EqYHVjfVVU6jztT",
        "plasmic_default_styles",
        "plasmic_mixins",
        styleTokensClassNames,
        "Button__root__cilx0",
        {
          Button__rootcolor_errorDestructive__cilx0AIiCx: hasVariant(
            $state,
            "color",
            "errorDestructive"
          ),
          Button__rootcolor_errorDestructive_type_bordered__cilx0AIiCxZReCv:
            hasVariant($state, "color", "errorDestructive") &&
            hasVariant($state, "type", "bordered"),
          Button__rootcolor_muted__cilx0J0HLs: hasVariant(
            $state,
            "color",
            "muted"
          ),
          Button__rootcolor_muted_type_bordered__cilx0J0HLsZReCv:
            hasVariant($state, "color", "muted") &&
            hasVariant($state, "type", "bordered"),
          Button__rootcolor_neutral__cilx0RaJ0T: hasVariant(
            $state,
            "color",
            "neutral"
          ),
          Button__rootcolor_neutral_type_bordered__cilx0RaJ0TZReCv:
            hasVariant($state, "color", "neutral") &&
            hasVariant($state, "type", "bordered"),
          Button__rootcolor_success__cilx0A24Md: hasVariant(
            $state,
            "color",
            "success"
          ),
          Button__rootcolor_success_type_bordered__cilx0A24MdZReCv:
            hasVariant($state, "color", "success") &&
            hasVariant($state, "type", "bordered"),
          Button__rootcolor_warning__cilx0Yqdrn: hasVariant(
            $state,
            "color",
            "warning"
          ),
          Button__rootcolor_warning_type_bordered__cilx0YqdrnZReCv:
            hasVariant($state, "color", "warning") &&
            hasVariant($state, "type", "bordered"),
          Button__rootflatSide_bottom__cilx0QX2Aa: hasVariant(
            $state,
            "flatSide",
            "bottom"
          ),
          Button__rootflatSide_left__cilx0JmSh6: hasVariant(
            $state,
            "flatSide",
            "left"
          ),
          Button__rootflatSide_right__cilx07XsKi: hasVariant(
            $state,
            "flatSide",
            "right"
          ),
          Button__rootflatSide_top__cilx0JHyG: hasVariant(
            $state,
            "flatSide",
            "top"
          ),
          Button__rooticonEnd__cilx0HmwSk: hasVariant(
            $state,
            "iconEnd",
            "iconEnd"
          ),
          Button__rooticonStart__cilx08ZWj5: hasVariant(
            $state,
            "iconStart",
            "iconStart"
          ),
          Button__rootroundedFull__cilx0U5Ej8: hasVariant(
            $state,
            "roundedFull",
            "roundedFull"
          ),
          Button__rootsize_extraLarge__cilx0TUpIm: hasVariant(
            $state,
            "size",
            "extraLarge"
          ),
          Button__rootsize_extraSmall__cilx0Tncmp: hasVariant(
            $state,
            "size",
            "extraSmall"
          ),
          Button__rootsize_large__cilx0KowZy: hasVariant(
            $state,
            "size",
            "large"
          ),
          Button__rootsize_small__cilx0Hj5ZR: hasVariant(
            $state,
            "size",
            "small"
          ),
          Button__roottype_bordered__cilx0ZReCv: hasVariant(
            $state,
            "type",
            "bordered"
          ),
          Button__roottype_soft__cilx093O2G: hasVariant($state, "type", "soft"),
          Button__roottype_soft_color_errorDestructive__cilx093O2GAIiCx:
            hasVariant($state, "color", "errorDestructive") &&
            hasVariant($state, "type", "soft"),
          Button__roottype_soft_color_muted__cilx093O2GJ0HLs:
            hasVariant($state, "color", "muted") &&
            hasVariant($state, "type", "soft"),
          Button__roottype_soft_color_neutral__cilx093O2GRaJ0T:
            hasVariant($state, "color", "neutral") &&
            hasVariant($state, "type", "soft"),
          Button__roottype_soft_color_success__cilx093O2GA24Md:
            hasVariant($state, "color", "success") &&
            hasVariant($state, "type", "soft"),
          Button__roottype_soft_color_warning__cilx093O2GYqdrn:
            hasVariant($state, "color", "warning") &&
            hasVariant($state, "type", "soft")
        }
      )}
      href={args.linkTo}
      isDisabled={args.disabled}
      onPress={args.onClick}
      plasmicUpdateVariant={updateVariant}
      resetsForm={args.resetsForm}
      submitsForm={args.submitsForm}
      target={(() => {
        try {
          return $props.openLinkInNewTab ? "_blank" : "_self";
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return undefined;
          }
          throw e;
        }
      })()}
    >
      {(
        hasVariant($state, "type", "bordered") && $ccVariants["pressed"]
          ? true
          : hasVariant($state, "type", "bordered") && $ccVariants["hovered"]
            ? true
            : hasVariant($state, "type", "soft")
              ? true
              : false
      ) ? (
        <div
          data-plasmic-name={"softBackground"}
          data-plasmic-override={overrides.softBackground}
          className={classNames(
            "plasmic_default__all",
            "Button__softBackground__jfFSv",
            {
              Button__softBackgroundcolor_errorDestructive__jfFSvAIiCx:
                hasVariant($state, "color", "errorDestructive"),
              Button__softBackgroundcolor_muted__jfFSvj0HLs: hasVariant(
                $state,
                "color",
                "muted"
              ),
              Button__softBackgroundcolor_neutral__jfFSvraJ0T: hasVariant(
                $state,
                "color",
                "neutral"
              ),
              Button__softBackgroundcolor_success__jfFSva24Md: hasVariant(
                $state,
                "color",
                "success"
              ),
              Button__softBackgroundcolor_warning__jfFSvYqdrn: hasVariant(
                $state,
                "color",
                "warning"
              ),
              Button__softBackgroundroundedFull__jfFSvu5Ej8: hasVariant(
                $state,
                "roundedFull",
                "roundedFull"
              ),
              Button__softBackgroundsize_large__jfFSvKowZy: hasVariant(
                $state,
                "size",
                "large"
              ),
              Button__softBackgroundtype_bordered__jfFSvzReCv: hasVariant(
                $state,
                "type",
                "bordered"
              ),
              Button__softBackgroundtype_soft__jfFSv93O2G: hasVariant(
                $state,
                "type",
                "soft"
              )
            }
          )}
        />
      ) : null}
      {(hasVariant($state, "type", "bordered") ? true : false) ? (
        <div
          data-plasmic-name={"border"}
          data-plasmic-override={overrides.border}
          className={classNames(
            "plasmic_default__all",
            "Button__border__nnbKs",
            {
              Button__bordercolor_errorDestructive__nnbKsaIiCx: hasVariant(
                $state,
                "color",
                "errorDestructive"
              ),
              Button__bordercolor_muted__nnbKSj0HLs: hasVariant(
                $state,
                "color",
                "muted"
              ),
              Button__bordercolor_muted_type_bordered__nnbKSj0HLsZReCv:
                hasVariant($state, "color", "muted") &&
                hasVariant($state, "type", "bordered"),
              Button__bordercolor_neutral__nnbKSraJ0T: hasVariant(
                $state,
                "color",
                "neutral"
              ),
              Button__bordercolor_success__nnbKSa24Md: hasVariant(
                $state,
                "color",
                "success"
              ),
              Button__bordercolor_warning__nnbKsYqdrn: hasVariant(
                $state,
                "color",
                "warning"
              ),
              Button__borderflatSide_bottom__nnbKSqX2Aa: hasVariant(
                $state,
                "flatSide",
                "bottom"
              ),
              Button__borderflatSide_left__nnbKsjmSh6: hasVariant(
                $state,
                "flatSide",
                "left"
              ),
              Button__borderflatSide_right__nnbKs7XsKi: hasVariant(
                $state,
                "flatSide",
                "right"
              ),
              Button__borderflatSide_top__nnbKsjHyG: hasVariant(
                $state,
                "flatSide",
                "top"
              ),
              Button__borderroundedFull__nnbKSu5Ej8: hasVariant(
                $state,
                "roundedFull",
                "roundedFull"
              ),
              Button__bordersize_large__nnbKsKowZy: hasVariant(
                $state,
                "size",
                "large"
              ),
              Button__bordertype_bordered__nnbKSzReCv: hasVariant(
                $state,
                "type",
                "bordered"
              ),
              Button__bordertype_soft__nnbKs93O2G: hasVariant(
                $state,
                "type",
                "soft"
              )
            }
          )}
        />
      ) : null}
      <div
        data-plasmic-name={"interactionEffect"}
        data-plasmic-override={overrides.interactionEffect}
        className={classNames(
          "plasmic_default__all",
          "Button__interactionEffect___8Icih",
          {
            Button__interactionEffectcolor_errorDestructive___8IcihAIiCx:
              hasVariant($state, "color", "errorDestructive"),
            Button__interactionEffectcolor_muted___8Icihj0HLs: hasVariant(
              $state,
              "color",
              "muted"
            ),
            Button__interactionEffectcolor_neutral___8IcihraJ0T: hasVariant(
              $state,
              "color",
              "neutral"
            ),
            Button__interactionEffectcolor_success___8Iciha24Md: hasVariant(
              $state,
              "color",
              "success"
            ),
            Button__interactionEffectcolor_success_type_bordered___8Iciha24MdZReCv:
              hasVariant($state, "color", "success") &&
              hasVariant($state, "type", "bordered"),
            Button__interactionEffectcolor_warning___8IcihYqdrn: hasVariant(
              $state,
              "color",
              "warning"
            ),
            Button__interactionEffectroundedFull___8Icihu5Ej8: hasVariant(
              $state,
              "roundedFull",
              "roundedFull"
            ),
            Button__interactionEffectsize_large___8IcihKowZy: hasVariant(
              $state,
              "size",
              "large"
            ),
            Button__interactionEffectsize_small___8Icihhj5ZR: hasVariant(
              $state,
              "size",
              "small"
            ),
            Button__interactionEffecttype_bordered___8IcihzReCv: hasVariant(
              $state,
              "type",
              "bordered"
            ),
            Button__interactionEffecttype_soft___8Icih93O2G: hasVariant(
              $state,
              "type",
              "soft"
            )
          }
        )}
        style={
          hasVariant($state, "type", "bordered") && $ccVariants["pressed"]
            ? { display: "block" }
            : undefined
        }
      />

      <div
        className={classNames(
          "plasmic_default__all",
          "Button__freeBox___8D8Ap",
          {
            Button__freeBoxcolor_neutral___8D8ApraJ0T: hasVariant(
              $state,
              "color",
              "neutral"
            ),
            Button__freeBoxcolor_success_type_bordered___8D8Apa24MdZReCv:
              hasVariant($state, "color", "success") &&
              hasVariant($state, "type", "bordered"),
            Button__freeBoxroundedFull___8D8Apu5Ej8: hasVariant(
              $state,
              "roundedFull",
              "roundedFull"
            ),
            Button__freeBoxsize_extraLarge___8D8AptUpIm: hasVariant(
              $state,
              "size",
              "extraLarge"
            ),
            Button__freeBoxsize_extraSmall___8D8Aptncmp: hasVariant(
              $state,
              "size",
              "extraSmall"
            ),
            Button__freeBoxsize_large___8D8ApKowZy: hasVariant(
              $state,
              "size",
              "large"
            ),
            Button__freeBoxsize_small___8D8Aphj5ZR: hasVariant(
              $state,
              "size",
              "small"
            ),
            Button__freeBoxtype_bordered___8D8ApzReCv: hasVariant(
              $state,
              "type",
              "bordered"
            )
          }
        )}
      >
        <div
          className={classNames(
            "plasmic_default__all",
            "Button__freeBox__v6I6S",
            {
              Button__freeBoxcolor_neutral__v6I6SraJ0T: hasVariant(
                $state,
                "color",
                "neutral"
              ),
              Button__freeBoxiconStart__v6I6S8ZWj5: hasVariant(
                $state,
                "iconStart",
                "iconStart"
              ),
              Button__freeBoxsize_extraLarge__v6I6StUpIm: hasVariant(
                $state,
                "size",
                "extraLarge"
              ),
              Button__freeBoxsize_large__v6I6SKowZy: hasVariant(
                $state,
                "size",
                "large"
              ),
              Button__freeBoxsize_small__v6I6Shj5ZR: hasVariant(
                $state,
                "size",
                "small"
              ),
              Button__freeBoxtype_bordered__v6I6SzReCv: hasVariant(
                $state,
                "type",
                "bordered"
              ),
              Button__freeBoxtype_soft_color_neutral__v6I6S93O2GRaJ0T:
                hasVariant($state, "color", "neutral") &&
                hasVariant($state, "type", "soft")
            }
          )}
        >
          {renderPlasmicSlot({
            defaultContents: (
              <CircleIcon
                className={classNames(
                  "plasmic_default__all",
                  "Button__svg__nNPe"
                )}
                role={"img"}
              />
            ),

            value: args.start,
            className: classNames("Button__slotTargetStart__dCyTt", {
              Button__slotTargetStartcolor_errorDestructive__dCyTtaIiCx:
                hasVariant($state, "color", "errorDestructive"),
              Button__slotTargetStartcolor_errorDestructive_type_bordered__dCyTtaIiCxZReCv:
                hasVariant($state, "color", "errorDestructive") &&
                hasVariant($state, "type", "bordered"),
              Button__slotTargetStartcolor_muted__dCyTTj0HLs: hasVariant(
                $state,
                "color",
                "muted"
              ),
              Button__slotTargetStartcolor_muted_type_bordered__dCyTTj0HLsZReCv:
                hasVariant($state, "color", "muted") &&
                hasVariant($state, "type", "bordered"),
              Button__slotTargetStartcolor_neutral__dCyTTraJ0T: hasVariant(
                $state,
                "color",
                "neutral"
              ),
              Button__slotTargetStartcolor_neutral_type_bordered__dCyTTraJ0TZReCv:
                hasVariant($state, "color", "neutral") &&
                hasVariant($state, "type", "bordered"),
              Button__slotTargetStartcolor_success__dCyTTa24Md: hasVariant(
                $state,
                "color",
                "success"
              ),
              Button__slotTargetStartcolor_success_type_bordered__dCyTTa24MdZReCv:
                hasVariant($state, "color", "success") &&
                hasVariant($state, "type", "bordered"),
              Button__slotTargetStartcolor_warning__dCyTtYqdrn: hasVariant(
                $state,
                "color",
                "warning"
              ),
              Button__slotTargetStartcolor_warning_type_bordered__dCyTtYqdrnZReCv:
                hasVariant($state, "color", "warning") &&
                hasVariant($state, "type", "bordered"),
              Button__slotTargetStarticonStart__dCyTt8ZWj5: hasVariant(
                $state,
                "iconStart",
                "iconStart"
              ),
              Button__slotTargetStartsize_extraLarge__dCyTTtUpIm: hasVariant(
                $state,
                "size",
                "extraLarge"
              ),
              Button__slotTargetStartsize_extraSmall__dCyTTtncmp: hasVariant(
                $state,
                "size",
                "extraSmall"
              ),
              Button__slotTargetStartsize_large__dCyTtKowZy: hasVariant(
                $state,
                "size",
                "large"
              ),
              Button__slotTargetStartsize_small__dCyTThj5ZR: hasVariant(
                $state,
                "size",
                "small"
              ),
              Button__slotTargetStarttype_bordered__dCyTTzReCv: hasVariant(
                $state,
                "type",
                "bordered"
              ),
              Button__slotTargetStarttype_soft__dCyTt93O2G: hasVariant(
                $state,
                "type",
                "soft"
              ),
              Button__slotTargetStarttype_soft_color_errorDestructive__dCyTt93O2GAIiCx:
                hasVariant($state, "color", "errorDestructive") &&
                hasVariant($state, "type", "soft"),
              Button__slotTargetStarttype_soft_color_muted__dCyTt93O2GJ0HLs:
                hasVariant($state, "color", "muted") &&
                hasVariant($state, "type", "soft"),
              Button__slotTargetStarttype_soft_color_neutral__dCyTt93O2GRaJ0T:
                hasVariant($state, "color", "neutral") &&
                hasVariant($state, "type", "soft"),
              Button__slotTargetStarttype_soft_color_success__dCyTt93O2GA24Md:
                hasVariant($state, "color", "success") &&
                hasVariant($state, "type", "soft"),
              Button__slotTargetStarttype_soft_color_warning__dCyTt93O2GYqdrn:
                hasVariant($state, "color", "warning") &&
                hasVariant($state, "type", "soft")
            })
          })}
        </div>
        {renderPlasmicSlot({
          defaultContents: (
            <div
              className={classNames(
                "plasmic_default__all",
                "__wab_text",
                "Button__text__ujVtg"
              )}
            >
              {"Text"}
            </div>
          ),
          value: args.label,
          className: classNames("Button__slotTargetLabel__nxdCe", {
            Button__slotTargetLabelcolor_errorDestructive__nxdCeaIiCx:
              hasVariant($state, "color", "errorDestructive"),
            Button__slotTargetLabelcolor_errorDestructive_type_bordered__nxdCeaIiCxZReCv:
              hasVariant($state, "color", "errorDestructive") &&
              hasVariant($state, "type", "bordered"),
            Button__slotTargetLabelcolor_muted__nxdCEj0HLs: hasVariant(
              $state,
              "color",
              "muted"
            ),
            Button__slotTargetLabelcolor_muted_type_bordered__nxdCEj0HLsZReCv:
              hasVariant($state, "color", "muted") &&
              hasVariant($state, "type", "bordered"),
            Button__slotTargetLabelcolor_neutral__nxdCEraJ0T: hasVariant(
              $state,
              "color",
              "neutral"
            ),
            Button__slotTargetLabelcolor_neutral_type_bordered__nxdCEraJ0TZReCv:
              hasVariant($state, "color", "neutral") &&
              hasVariant($state, "type", "bordered"),
            Button__slotTargetLabelcolor_success__nxdCEa24Md: hasVariant(
              $state,
              "color",
              "success"
            ),
            Button__slotTargetLabelcolor_success_type_bordered__nxdCEa24MdZReCv:
              hasVariant($state, "color", "success") &&
              hasVariant($state, "type", "bordered"),
            Button__slotTargetLabelcolor_warning__nxdCeYqdrn: hasVariant(
              $state,
              "color",
              "warning"
            ),
            Button__slotTargetLabelcolor_warning_type_bordered__nxdCeYqdrnZReCv:
              hasVariant($state, "color", "warning") &&
              hasVariant($state, "type", "bordered"),
            Button__slotTargetLabeliconEnd__nxdCEhmwSk: hasVariant(
              $state,
              "iconEnd",
              "iconEnd"
            ),
            Button__slotTargetLabeliconStart__nxdCe8ZWj5: hasVariant(
              $state,
              "iconStart",
              "iconStart"
            ),
            Button__slotTargetLabelsize_extraLarge__nxdCEtUpIm: hasVariant(
              $state,
              "size",
              "extraLarge"
            ),
            Button__slotTargetLabelsize_extraSmall__nxdCEtncmp: hasVariant(
              $state,
              "size",
              "extraSmall"
            ),
            Button__slotTargetLabelsize_large__nxdCeKowZy: hasVariant(
              $state,
              "size",
              "large"
            ),
            Button__slotTargetLabelsize_small__nxdCEhj5ZR: hasVariant(
              $state,
              "size",
              "small"
            ),
            Button__slotTargetLabeltype_bordered__nxdCEzReCv: hasVariant(
              $state,
              "type",
              "bordered"
            ),
            Button__slotTargetLabeltype_soft__nxdCe93O2G: hasVariant(
              $state,
              "type",
              "soft"
            ),
            Button__slotTargetLabeltype_soft_color_errorDestructive__nxdCe93O2GAIiCx:
              hasVariant($state, "color", "errorDestructive") &&
              hasVariant($state, "type", "soft"),
            Button__slotTargetLabeltype_soft_color_muted__nxdCe93O2GJ0HLs:
              hasVariant($state, "color", "muted") &&
              hasVariant($state, "type", "soft"),
            Button__slotTargetLabeltype_soft_color_neutral__nxdCe93O2GRaJ0T:
              hasVariant($state, "color", "neutral") &&
              hasVariant($state, "type", "soft"),
            Button__slotTargetLabeltype_soft_color_success__nxdCe93O2GA24Md:
              hasVariant($state, "color", "success") &&
              hasVariant($state, "type", "soft"),
            Button__slotTargetLabeltype_soft_color_warning__nxdCe93O2GYqdrn:
              hasVariant($state, "color", "warning") &&
              hasVariant($state, "type", "soft")
          })
        })}
        <div
          className={classNames(
            "plasmic_default__all",
            "Button__freeBox__te8I2",
            {
              Button__freeBoxiconEnd__te8I2HmwSk: hasVariant(
                $state,
                "iconEnd",
                "iconEnd"
              ),
              Button__freeBoxsize_extraLarge__te8I2TUpIm: hasVariant(
                $state,
                "size",
                "extraLarge"
              ),
              Button__freeBoxsize_large__te8I2KowZy: hasVariant(
                $state,
                "size",
                "large"
              ),
              Button__freeBoxsize_small__te8I2Hj5ZR: hasVariant(
                $state,
                "size",
                "small"
              )
            }
          )}
        >
          {renderPlasmicSlot({
            defaultContents: (
              <ChevronDownIcon
                className={classNames(
                  "plasmic_default__all",
                  "Button__svg__w3L46"
                )}
                role={"img"}
              />
            ),

            value: args.end,
            className: classNames("Button__slotTargetEnd__cQbC", {
              Button__slotTargetEndcolor_errorDestructive__cQbCaIiCx:
                hasVariant($state, "color", "errorDestructive"),
              Button__slotTargetEndcolor_errorDestructive_type_bordered__cQbCaIiCxZReCv:
                hasVariant($state, "color", "errorDestructive") &&
                hasVariant($state, "type", "bordered"),
              Button__slotTargetEndcolor_muted__cQbCj0HLs: hasVariant(
                $state,
                "color",
                "muted"
              ),
              Button__slotTargetEndcolor_muted_type_bordered__cQbCj0HLsZReCv:
                hasVariant($state, "color", "muted") &&
                hasVariant($state, "type", "bordered"),
              Button__slotTargetEndcolor_neutral__cQbCraJ0T: hasVariant(
                $state,
                "color",
                "neutral"
              ),
              Button__slotTargetEndcolor_neutral_type_bordered__cQbCraJ0TZReCv:
                hasVariant($state, "color", "neutral") &&
                hasVariant($state, "type", "bordered"),
              Button__slotTargetEndcolor_success__cQbCa24Md: hasVariant(
                $state,
                "color",
                "success"
              ),
              Button__slotTargetEndcolor_success_type_bordered__cQbCa24MdZReCv:
                hasVariant($state, "color", "success") &&
                hasVariant($state, "type", "bordered"),
              Button__slotTargetEndcolor_warning__cQbCYqdrn: hasVariant(
                $state,
                "color",
                "warning"
              ),
              Button__slotTargetEndcolor_warning_type_bordered__cQbCYqdrnZReCv:
                hasVariant($state, "color", "warning") &&
                hasVariant($state, "type", "bordered"),
              Button__slotTargetEndiconEnd__cQbChmwSk: hasVariant(
                $state,
                "iconEnd",
                "iconEnd"
              ),
              Button__slotTargetEndiconStart__cQbC8ZWj5: hasVariant(
                $state,
                "iconStart",
                "iconStart"
              ),
              Button__slotTargetEndsize_extraLarge__cQbCtUpIm: hasVariant(
                $state,
                "size",
                "extraLarge"
              ),
              Button__slotTargetEndsize_extraSmall__cQbCtncmp: hasVariant(
                $state,
                "size",
                "extraSmall"
              ),
              Button__slotTargetEndsize_large__cQbCKowZy: hasVariant(
                $state,
                "size",
                "large"
              ),
              Button__slotTargetEndsize_small__cQbChj5ZR: hasVariant(
                $state,
                "size",
                "small"
              ),
              Button__slotTargetEndtype_bordered__cQbCzReCv: hasVariant(
                $state,
                "type",
                "bordered"
              ),
              Button__slotTargetEndtype_soft__cQbC93O2G: hasVariant(
                $state,
                "type",
                "soft"
              ),
              Button__slotTargetEndtype_soft_color_errorDestructive__cQbC93O2GAIiCx:
                hasVariant($state, "color", "errorDestructive") &&
                hasVariant($state, "type", "soft"),
              Button__slotTargetEndtype_soft_color_muted__cQbC93O2GJ0HLs:
                hasVariant($state, "color", "muted") &&
                hasVariant($state, "type", "soft"),
              Button__slotTargetEndtype_soft_color_neutral__cQbC93O2GRaJ0T:
                hasVariant($state, "color", "neutral") &&
                hasVariant($state, "type", "soft"),
              Button__slotTargetEndtype_soft_color_success__cQbC93O2GA24Md:
                hasVariant($state, "color", "success") &&
                hasVariant($state, "type", "soft"),
              Button__slotTargetEndtype_soft_color_warning__cQbC93O2GYqdrn:
                hasVariant($state, "color", "warning") &&
                hasVariant($state, "type", "soft")
            })
          })}
        </div>
      </div>
    </BaseButton>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "softBackground", "border", "interactionEffect"],
  softBackground: ["softBackground"],
  border: ["border"],
  interactionEffect: ["interactionEffect"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: typeof BaseButton;
  softBackground: "div";
  border: "div";
  interactionEffect: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicButton__VariantsArgs;
    args?: PlasmicButton__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicButton__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicButton__ArgProps,
          internalVariantPropNames: PlasmicButton__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicButton";
  } else {
    func.displayName = `PlasmicButton.${nodeName}`;
  }
  return func;
}

export const PlasmicButton = Object.assign(
  // Top-level PlasmicButton renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    softBackground: makeNodeComponent("softBackground"),
    border: makeNodeComponent("border"),
    interactionEffect: makeNodeComponent("interactionEffect"),

    // Metadata about props expected for PlasmicButton
    internalVariantProps: PlasmicButton__VariantProps,
    internalArgProps: PlasmicButton__ArgProps
  }
);

export const PlasmicButton__HeadOptions = {
  meta: [{ name: "twitter:card", content: "summary" }],

  links: []
} as Record<"meta" | "links", Array<Record<string, string>>>;

export default PlasmicButton;
/* prettier-ignore-end */
