/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4WZ4je7EqYHVjfVVU6jztT
// Component: XqDLkPuFzm0v

import * as React from "react";

import { useRouter, Link } from "@tanstack/react-router";
import type { LinkProps } from "@tanstack/react-router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";
import "../../plasmic/plasmic__default_style.css"; // plasmic-import: global/defaultcss

import "./plasmic.css"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/projectcss
import "./PlasmicSignUpEditable.css"; // plasmic-import: XqDLkPuFzm0v/css

import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: 235GWjmNq59s/icon
import Icon21Icon from "./icons/PlasmicIcon__Icon21"; // plasmic-import: 7ug0X4lwJM2I/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicSignUpEditable__VariantMembers = {};
export type PlasmicSignUpEditable__VariantsArgs = {};
type VariantPropType = keyof PlasmicSignUpEditable__VariantsArgs;
export const PlasmicSignUpEditable__VariantProps = new Array<VariantPropType>();

export type PlasmicSignUpEditable__ArgsType = {};
type ArgPropType = keyof PlasmicSignUpEditable__ArgsType;
export const PlasmicSignUpEditable__ArgProps = new Array<ArgPropType>();

export type PlasmicSignUpEditable__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<"header">;
  strong?: Flex__<"strong">;
  h1?: Flex__<"h1">;
  p?: Flex__<"p">;
  form?: Flex__<"form">;
  textbox?: Flex__<"input">;
  textbox2?: Flex__<"input">;
  password?: Flex__<"input">;
  footer?: Flex__<"footer">;
};

export interface DefaultSignUpEditableProps {}

const $$ = {};

function useTanStackRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSignUpEditable__RenderFunc(props: {
  variants: PlasmicSignUpEditable__VariantsArgs;
  args: PlasmicSignUpEditable__ArgsType;
  overrides: PlasmicSignUpEditable__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __tanstackRouter = useTanStackRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "textbox.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "textbox2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "password.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "plasmic_default__all",
            "root_reset_4WZ4je7EqYHVjfVVU6jztT",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            "SignUpEditable__root__v9Td"
          )}
        >
          <div
            className={classNames(
              "plasmic_default__all",
              "SignUpEditable__freeBox__k3UEo"
            )}
            style={{
              backgroundImage:
                "radial-gradient(oklch(0.24 0.008 70) 0.45px, rgba(0, 0, 0, 0) 0.45px)",
              backgroundSize: "4px 4px",
              backgroundPosition: "0% 0%"
            }}
          >
            <header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames(
                "plasmic_default__all",
                "SignUpEditable__header__m14Gl"
              )}
              style={{
                backgroundImage: "none",
                backgroundSize: "auto",
                backgroundPosition: "0% 0%"
              }}
            >
              <PlasmicLink__
                aria-label={"Kaizen, in\u00edcio"}
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__a",
                  "plasmic_default__a__4WZ4j",
                  "SignUpEditable__link__mJa9G"
                )}
                component={Link}
                href={"/"}
                platform={"tanstack"}
                style={{
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%"
                }}
              >
                <Icon3Icon
                  className={classNames(
                    "plasmic_default__all",
                    "SignUpEditable__svg__lZYwo"
                  )}
                  role={"img"}
                />

                <strong
                  data-plasmic-name={"strong"}
                  data-plasmic-override={overrides.strong}
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__strong",
                    "plasmic_default__strong__4WZ4j",
                    "SignUpEditable__strong___2WcY2"
                  )}
                  style={{
                    backgroundImage: "none",
                    backgroundSize: "auto",
                    backgroundPosition: "0% 0%"
                  }}
                >
                  <span
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__span",
                      "plasmic_default__span__4WZ4j",
                      "__wab_text",
                      "SignUpEditable__span__ljjjs"
                    )}
                  >
                    {"Kaizen"}
                  </span>
                </strong>
              </PlasmicLink__>
              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "SignUpEditable__span__wGbYy"
                )}
                style={{
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%"
                }}
              />

              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "SignUpEditable__span__qAhmo"
                )}
                style={{
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%"
                }}
              >
                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "__wab_text",
                    "SignUpEditable__span__iiQys"
                  )}
                >
                  {"Ember"}
                </span>
              </span>
              <button
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__button",
                  "plasmic_default__button__4WZ4j",
                  "SignUpEditable__button__ws3Q"
                )}
                style={{
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0px 0px"
                }}
                type={"button"}
              >
                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "__wab_text",
                    "SignUpEditable__span___9Dhis"
                  )}
                >
                  {"Sobre"}
                </span>
              </button>
              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "SignUpEditable__span__vsIlh"
                )}
                style={{
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%"
                }}
              >
                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "__wab_text",
                    "SignUpEditable__span__zE4Ev"
                  )}
                >
                  {"v0.1.0-alpha"}
                </span>
              </span>
            </header>
            <div
              className={classNames(
                "plasmic_default__all",
                "SignUpEditable__freeBox___6Fqlp"
              )}
              style={{
                backgroundImage: "none",
                backgroundSize: "auto",
                backgroundPosition: "0% 0%",
                gridTemplateColumns: "1232.8px",
                gridTemplateRows: "654px"
              }}
            >
              <div
                className={classNames(
                  "plasmic_default__all",
                  "SignUpEditable__freeBox__l0MwS"
                )}
                style={{
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%",
                  gridArea: "auto"
                }}
              >
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "SignUpEditable__freeBox__nXxx1"
                  )}
                  style={{
                    backgroundImage: "none",
                    backgroundSize: "auto",
                    backgroundPosition: "0% 0%"
                  }}
                >
                  <span
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__span",
                      "plasmic_default__span__4WZ4j",
                      "SignUpEditable__span__jfq24"
                    )}
                    style={{
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%"
                    }}
                  />

                  <span
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__span",
                      "plasmic_default__span__4WZ4j",
                      "SignUpEditable__span__ucpR"
                    )}
                    style={{
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%"
                    }}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "SignUpEditable__span__ttyug"
                      )}
                    >
                      {"Acesso ao sistema"}
                    </span>
                  </span>
                  <span
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__span",
                      "plasmic_default__span__4WZ4j",
                      "SignUpEditable__span__mAkd"
                    )}
                    style={{
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%"
                    }}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "SignUpEditable__span__yZ8Cu"
                      )}
                    >
                      {"02"}
                    </span>
                  </span>
                </div>
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "SignUpEditable__freeBox___5UpP"
                  )}
                  style={{
                    backgroundImage: "none",
                    backgroundSize: "auto",
                    backgroundPosition: "0% 0%"
                  }}
                >
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "SignUpEditable__freeBox__yZtHj"
                    )}
                    style={{
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%"
                    }}
                  >
                    <Icon21Icon
                      className={classNames(
                        "plasmic_default__all",
                        "SignUpEditable__svg__df3U0"
                      )}
                      role={"img"}
                    />

                    <h1
                      data-plasmic-name={"h1"}
                      data-plasmic-override={overrides.h1}
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__h1",
                        "plasmic_default__h1__4WZ4j",
                        "SignUpEditable__h1__ui77U"
                      )}
                      style={{
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%"
                      }}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "SignUpEditable__span__wsSmx"
                        )}
                      >
                        {"Continue sua jornada"}
                      </span>
                    </h1>
                    <p
                      data-plasmic-name={"p"}
                      data-plasmic-override={overrides.p}
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__p",
                        "plasmic_default__p__4WZ4j",
                        "SignUpEditable__p__zhzNe"
                      )}
                      style={{
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%"
                      }}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "SignUpEditable__span__oewUo"
                        )}
                      >
                        {"Entre para continuar sua jornada."}
                      </span>
                    </p>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "SignUpEditable__freeBox__opnwk"
                    )}
                    style={{
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%"
                    }}
                  >
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "SignUpEditable__freeBox__i4Tbb"
                      )}
                      style={{
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        gridTemplateColumns: "201.4px 201.4px",
                        gridTemplateRows: "44px"
                      }}
                    >
                      <button
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__button",
                          "plasmic_default__button__4WZ4j",
                          "SignUpEditable__button__j5QJj"
                        )}
                        id={"radix-_R_59aq_-trigger-login"}
                        style={{
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          gridArea: "auto"
                        }}
                        type={"button"}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "SignUpEditable__span__joj4A"
                          )}
                        >
                          {"Entrar"}
                        </span>
                      </button>
                      <button
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__button",
                          "plasmic_default__button__4WZ4j",
                          "SignUpEditable__button__xr7C1"
                        )}
                        id={"radix-_R_59aq_-trigger-signup"}
                        style={{
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          gridArea: "auto"
                        }}
                        type={"button"}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "SignUpEditable__span__wzJkP"
                          )}
                        >
                          {"Criar conta"}
                        </span>
                      </button>
                    </div>
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "SignUpEditable__freeBox__gxuyd"
                      )}
                      id={"radix-_R_59aq_-content-signup"}
                      style={{
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%"
                      }}
                    >
                      <form
                        data-plasmic-name={"form"}
                        data-plasmic-override={overrides.form}
                        className={classNames(
                          "plasmic_default__all",
                          "SignUpEditable__form__w0GDc"
                        )}
                        style={{
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%"
                        }}
                      >
                        <div
                          className={classNames(
                            "plasmic_default__all",
                            "SignUpEditable__freeBox__o1N6"
                          )}
                          style={{
                            backgroundImage: "none",
                            backgroundSize: "auto",
                            backgroundPosition: "0% 0%"
                          }}
                        >
                          <label
                            className={classNames(
                              "plasmic_default__all",
                              "SignUpEditable__label__qAtQw"
                            )}
                            style={{
                              backgroundImage: "none",
                              backgroundSize: "auto",
                              backgroundPosition: "0% 0%"
                            }}
                          >
                            <span
                              className={classNames(
                                "plasmic_default__all",
                                "plasmic_default__span",
                                "plasmic_default__span__4WZ4j",
                                "__wab_text",
                                "SignUpEditable__span__pRBa"
                              )}
                            >
                              {"Nome do personagem"}
                            </span>
                          </label>
                          <input
                            data-plasmic-name={"textbox"}
                            data-plasmic-override={overrides.textbox}
                            className={classNames(
                              "plasmic_default__all",
                              "plasmic_default__input",
                              "plasmic_default__input__4WZ4j",
                              "SignUpEditable__textbox__dyDs4"
                            )}
                            id={"signup-character"}
                            name={"characterName"}
                            onChange={async (...eventArgs: any) => {
                              (e => {
                                generateStateOnChangeProp($state, [
                                  "textbox",
                                  "value"
                                ])(e.target.value);
                              }).apply(null, eventArgs);
                            }}
                            placeholder={"Ex: Aragorn das Tarefas"}
                            ref={ref => {
                              $refs["textbox"] = ref;
                            }}
                            style={{
                              backgroundImage: "none",
                              backgroundSize: "auto",
                              backgroundPosition: "0% 0%"
                            }}
                            value={
                              generateStateValueProp($state, [
                                "textbox",
                                "value"
                              ]) ?? ""
                            }
                          />
                        </div>
                        <div
                          className={classNames(
                            "plasmic_default__all",
                            "SignUpEditable__freeBox__fgILh"
                          )}
                          style={{
                            backgroundImage: "none",
                            backgroundSize: "auto",
                            backgroundPosition: "0% 0%"
                          }}
                        >
                          <label
                            className={classNames(
                              "plasmic_default__all",
                              "SignUpEditable__label__zXpa6"
                            )}
                            style={{
                              backgroundImage: "none",
                              backgroundSize: "auto",
                              backgroundPosition: "0% 0%"
                            }}
                          >
                            <span
                              className={classNames(
                                "plasmic_default__all",
                                "plasmic_default__span",
                                "plasmic_default__span__4WZ4j",
                                "__wab_text",
                                "SignUpEditable__span__fH1Y2"
                              )}
                            >
                              {"Email"}
                            </span>
                          </label>
                          <input
                            data-plasmic-name={"textbox2"}
                            data-plasmic-override={overrides.textbox2}
                            className={classNames(
                              "plasmic_default__all",
                              "plasmic_default__input",
                              "plasmic_default__input__4WZ4j",
                              "SignUpEditable__textbox2__ujmVl"
                            )}
                            id={"signup-email"}
                            name={"email"}
                            onChange={async (...eventArgs: any) => {
                              (e => {
                                generateStateOnChangeProp($state, [
                                  "textbox2",
                                  "value"
                                ])(e.target.value);
                              }).apply(null, eventArgs);
                            }}
                            ref={ref => {
                              $refs["textbox2"] = ref;
                            }}
                            style={{
                              backgroundImage: "none",
                              backgroundSize: "auto",
                              backgroundPosition: "0% 0%"
                            }}
                            type={"email"}
                            value={
                              generateStateValueProp($state, [
                                "textbox2",
                                "value"
                              ]) ?? ""
                            }
                          />
                        </div>
                        <div
                          className={classNames(
                            "plasmic_default__all",
                            "SignUpEditable__freeBox__bFgg"
                          )}
                          style={{
                            backgroundImage: "none",
                            backgroundSize: "auto",
                            backgroundPosition: "0% 0%"
                          }}
                        >
                          <label
                            className={classNames(
                              "plasmic_default__all",
                              "SignUpEditable__label__moTVn"
                            )}
                            style={{
                              backgroundImage: "none",
                              backgroundSize: "auto",
                              backgroundPosition: "0% 0%"
                            }}
                          >
                            <span
                              className={classNames(
                                "plasmic_default__all",
                                "plasmic_default__span",
                                "plasmic_default__span__4WZ4j",
                                "__wab_text",
                                "SignUpEditable__span__myQ1I"
                              )}
                            >
                              {"Senha"}
                            </span>
                          </label>
                          <input
                            data-plasmic-name={"password"}
                            data-plasmic-override={overrides.password}
                            className={classNames(
                              "plasmic_default__all",
                              "plasmic_default__input",
                              "plasmic_default__input__4WZ4j",
                              "SignUpEditable__password__izY2J"
                            )}
                            id={"signup-password"}
                            name={"password"}
                            onChange={async (...eventArgs: any) => {
                              (e => {
                                generateStateOnChangeProp($state, [
                                  "password",
                                  "value"
                                ])(e.target.value);
                              }).apply(null, eventArgs);
                            }}
                            ref={ref => {
                              $refs["password"] = ref;
                            }}
                            style={{
                              backgroundImage: "none",
                              backgroundSize: "auto",
                              backgroundPosition: "0% 0%"
                            }}
                            type={"password"}
                            value={
                              generateStateValueProp($state, [
                                "password",
                                "value"
                              ]) ?? ""
                            }
                          />
                        </div>
                        <button
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__button",
                            "plasmic_default__button__4WZ4j",
                            "SignUpEditable__button__qmEy"
                          )}
                          style={{
                            backgroundImage: "none",
                            backgroundSize: "auto",
                            backgroundPosition: "0% 0%"
                          }}
                          type={"submit"}
                        >
                          <span
                            className={classNames(
                              "plasmic_default__all",
                              "plasmic_default__span",
                              "plasmic_default__span__4WZ4j",
                              "__wab_text",
                              "SignUpEditable__span___2QEqK"
                            )}
                          >
                            {"Criar conta"}
                          </span>
                        </button>
                      </form>
                    </div>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "SignUpEditable__freeBox__ysUkf"
                    )}
                    style={{
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%"
                    }}
                  >
                    <PlasmicLink__
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__a",
                        "plasmic_default__a__4WZ4j",
                        "SignUpEditable__link__rlZq8"
                      )}
                      component={Link}
                      href={"/"}
                      platform={"tanstack"}
                      style={{
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%"
                      }}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "SignUpEditable__span__qc86L"
                        )}
                      >
                        {"Voltar ao in\u00edcio"}
                      </span>
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
            </div>
            <footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(
                "plasmic_default__all",
                "SignUpEditable__footer__rJleA"
              )}
              style={{
                backgroundImage: "none",
                backgroundSize: "auto",
                backgroundPosition: "0% 0%"
              }}
            >
              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "SignUpEditable__span__rYyGu"
                )}
                style={{
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%"
                }}
              >
                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "__wab_text",
                    "SignUpEditable__span__oNhi2"
                  )}
                >
                  {'Kaizen \u2014 v0.1.0-alpha "Ember"'}
                </span>
              </span>
              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "SignUpEditable__span__y2TJo"
                )}
                style={{
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%"
                }}
              >
                <Icon3Icon
                  className={classNames(
                    "plasmic_default__all",
                    "SignUpEditable__svg__lLuNu"
                  )}
                  role={"img"}
                />

                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "__wab_text",
                    "SignUpEditable__span__catwq"
                  )}
                >
                  {"Um passo de cada vez."}
                </span>
              </span>
            </footer>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "strong",
    "h1",
    "p",
    "form",
    "textbox",
    "textbox2",
    "password",
    "footer"
  ],
  header: ["header", "strong"],
  strong: ["strong"],
  h1: ["h1"],
  p: ["p"],
  form: ["form", "textbox", "textbox2", "password"],
  textbox: ["textbox"],
  textbox2: ["textbox2"],
  password: ["password"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: "header";
  strong: "strong";
  h1: "h1";
  p: "p";
  form: "form";
  textbox: "input";
  textbox2: "input";
  password: "input";
  footer: "footer";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSignUpEditable__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSignUpEditable__VariantsArgs;
    args?: PlasmicSignUpEditable__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicSignUpEditable__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicSignUpEditable__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSignUpEditable__ArgProps,
          internalVariantPropNames: PlasmicSignUpEditable__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSignUpEditable__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSignUpEditable";
  } else {
    func.displayName = `PlasmicSignUpEditable.${nodeName}`;
  }
  return func;
}

export const PlasmicSignUpEditable = Object.assign(
  // Top-level PlasmicSignUpEditable renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    strong: makeNodeComponent("strong"),
    h1: makeNodeComponent("h1"),
    p: makeNodeComponent("p"),
    form: makeNodeComponent("form"),
    textbox: makeNodeComponent("textbox"),
    textbox2: makeNodeComponent("textbox2"),
    password: makeNodeComponent("password"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicSignUpEditable
    internalVariantProps: PlasmicSignUpEditable__VariantProps,
    internalArgProps: PlasmicSignUpEditable__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/sign-up-editable",
      pagePath: "/sign-up-editable",
      params: {},
      query: {}
    })
  }
);

export const PlasmicSignUpEditable__HeadOptions = {
  meta: [{ name: "twitter:card", content: "summary" }],

  links: []
} as Record<"meta" | "links", Array<Record<string, string>>>;

export default PlasmicSignUpEditable;
/* prettier-ignore-end */
