/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4WZ4je7EqYHVjfVVU6jztT

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantsp1KK6JEoKz } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: P1K_K6jEo_kz/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantsp1KK6JEoKz
});
