/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4WZ4je7EqYHVjfVVU6jztT
// Component: jCrkMHkNi70H

import * as React from "react";

import { useRouter, Link } from "@tanstack/react-router";
import type { LinkProps } from "@tanstack/react-router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";
import "../../plasmic/plasmic__default_style.css"; // plasmic-import: global/defaultcss

import "./plasmic.css"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/projectcss
import "./PlasmicLoginEditable.css"; // plasmic-import: jCrkMHkNi70H/css

import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: 235GWjmNq59s/icon
import Icon21Icon from "./icons/PlasmicIcon__Icon21"; // plasmic-import: 7ug0X4lwJM2I/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicLoginEditable__VariantMembers = {};
export type PlasmicLoginEditable__VariantsArgs = {};
type VariantPropType = keyof PlasmicLoginEditable__VariantsArgs;
export const PlasmicLoginEditable__VariantProps = new Array<VariantPropType>();

export type PlasmicLoginEditable__ArgsType = {};
type ArgPropType = keyof PlasmicLoginEditable__ArgsType;
export const PlasmicLoginEditable__ArgProps = new Array<ArgPropType>();

export type PlasmicLoginEditable__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<"header">;
  strong?: Flex__<"strong">;
  h1?: Flex__<"h1">;
  p?: Flex__<"p">;
  form?: Flex__<"form">;
  textbox?: Flex__<"input">;
  password?: Flex__<"input">;
  footer?: Flex__<"footer">;
};

export interface DefaultLoginEditableProps {}

const $$ = {};

function useTanStackRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicLoginEditable__RenderFunc(props: {
  variants: PlasmicLoginEditable__VariantsArgs;
  args: PlasmicLoginEditable__ArgsType;
  overrides: PlasmicLoginEditable__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __tanstackRouter = useTanStackRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "textbox.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      },
      {
        path: "password.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $q, $ctx }) => undefined
      }
    ],
    [$props, $ctx, $refs]
  );

  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $q: {},
    $refs
  });

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "plasmic_default__all",
            "root_reset_4WZ4je7EqYHVjfVVU6jztT",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            "LoginEditable__root__lwu17"
          )}
        >
          <div
            className={classNames(
              "plasmic_default__all",
              "LoginEditable__freeBox__iNCc"
            )}
            style={{
              flexFlow: "column",
              gridTemplateColumns: "none",
              gridArea: "auto",
              backgroundImage:
                "radial-gradient(oklch(0.24 0.008 70) 0.45px, rgba(0, 0, 0, 0) 0.45px)",
              backgroundSize: "4px 4px",
              backgroundPosition: "0% 0%",
              backgroundRepeat: "repeat"
            }}
          >
            <header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames(
                "plasmic_default__all",
                "LoginEditable__header__lOXy"
              )}
              style={{
                flexFlow: "row",
                gridTemplateColumns: "none",
                gridArea: "auto",
                backgroundImage: "none",
                backgroundSize: "auto",
                backgroundPosition: "0% 0%",
                backgroundRepeat: "repeat"
              }}
            >
              <PlasmicLink__
                aria-label={"Kaizen, in\u00edcio"}
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__a",
                  "plasmic_default__a__4WZ4j",
                  "LoginEditable__link__gosTr"
                )}
                component={Link}
                href={"/"}
                platform={"tanstack"}
                style={{
                  flexFlow: "row",
                  gridTemplateColumns: "none",
                  gridArea: "auto",
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%",
                  backgroundRepeat: "repeat"
                }}
              >
                <Icon3Icon
                  className={classNames(
                    "plasmic_default__all",
                    "LoginEditable__svg___66Vbz"
                  )}
                  role={"img"}
                />

                <strong
                  data-plasmic-name={"strong"}
                  data-plasmic-override={overrides.strong}
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__strong",
                    "plasmic_default__strong__4WZ4j",
                    "LoginEditable__strong__vavWa"
                  )}
                  style={{
                    flexFlow: "row",
                    gridTemplateColumns: "none",
                    gridArea: "auto",
                    backgroundImage: "none",
                    backgroundSize: "auto",
                    backgroundPosition: "0% 0%",
                    backgroundRepeat: "repeat"
                  }}
                >
                  <span
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__span",
                      "plasmic_default__span__4WZ4j",
                      "__wab_text",
                      "LoginEditable__span__fki18"
                    )}
                  >
                    {"Kaizen"}
                  </span>
                </strong>
              </PlasmicLink__>
              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "LoginEditable__span__yio4V"
                )}
                style={{
                  flexFlow: "row",
                  gridTemplateColumns: "none",
                  gridArea: "auto",
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%",
                  backgroundRepeat: "repeat"
                }}
              />

              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "LoginEditable__span__bKw4T"
                )}
                style={{
                  flexFlow: "row",
                  gridTemplateColumns: "none",
                  gridArea: "auto",
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%",
                  backgroundRepeat: "repeat"
                }}
              >
                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "__wab_text",
                    "LoginEditable__span__uREa2"
                  )}
                >
                  {"Ember"}
                </span>
              </span>
              <button
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__button",
                  "plasmic_default__button__4WZ4j",
                  "LoginEditable__button__ba57G"
                )}
                style={{
                  flexFlow: "row",
                  gridTemplateColumns: "none",
                  gridArea: "auto",
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0px 0px",
                  backgroundRepeat: "repeat"
                }}
                type={"button"}
              >
                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "__wab_text",
                    "LoginEditable__span__idZ6K"
                  )}
                >
                  {"Sobre"}
                </span>
              </button>
              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "LoginEditable__span__tm91"
                )}
                style={{
                  flexFlow: "row",
                  gridTemplateColumns: "none",
                  gridArea: "auto",
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%",
                  backgroundRepeat: "repeat"
                }}
              >
                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "__wab_text",
                    "LoginEditable__span__t7Dxt"
                  )}
                >
                  {"v0.1.0-alpha"}
                </span>
              </span>
            </header>
            <div
              className={classNames(
                "plasmic_default__all",
                "LoginEditable__freeBox__xqdVc"
              )}
              style={{
                flexFlow: "row",
                gridTemplateColumns: "1248px",
                gridArea: "auto",
                backgroundImage: "none",
                backgroundSize: "auto",
                backgroundPosition: "0% 0%",
                backgroundRepeat: "repeat"
              }}
            >
              <div
                className={classNames(
                  "plasmic_default__all",
                  "LoginEditable__freeBox__zoIlJ"
                )}
                style={{
                  flexFlow: "row",
                  gridTemplateColumns: "none",
                  gridArea: "auto",
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%",
                  backgroundRepeat: "repeat"
                }}
              >
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "LoginEditable__freeBox___5Ipu4"
                  )}
                  style={{
                    flexFlow: "row",
                    gridTemplateColumns: "none",
                    gridArea: "auto",
                    backgroundImage: "none",
                    backgroundSize: "auto",
                    backgroundPosition: "0% 0%",
                    backgroundRepeat: "repeat"
                  }}
                >
                  <span
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__span",
                      "plasmic_default__span__4WZ4j",
                      "LoginEditable__span__osqa5"
                    )}
                    style={{
                      flexFlow: "row",
                      gridTemplateColumns: "none",
                      gridArea: "auto",
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%",
                      backgroundRepeat: "repeat"
                    }}
                  />

                  <span
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__span",
                      "plasmic_default__span__4WZ4j",
                      "LoginEditable__span__osll0"
                    )}
                    style={{
                      flexFlow: "row",
                      gridTemplateColumns: "none",
                      gridArea: "auto",
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%",
                      backgroundRepeat: "repeat"
                    }}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "LoginEditable__span___8E40B"
                      )}
                    >
                      {"Acesso ao sistema"}
                    </span>
                  </span>
                  <span
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__span",
                      "plasmic_default__span__4WZ4j",
                      "LoginEditable__span__iVsTi"
                    )}
                    style={{
                      flexFlow: "row",
                      gridTemplateColumns: "none",
                      gridArea: "auto",
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%",
                      backgroundRepeat: "repeat"
                    }}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "LoginEditable__span__yIdu"
                      )}
                    >
                      {"02"}
                    </span>
                  </span>
                </div>
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "LoginEditable__freeBox__qFD"
                  )}
                  style={{
                    flexFlow: "row",
                    gridTemplateColumns: "none",
                    gridArea: "auto",
                    backgroundImage: "none",
                    backgroundSize: "auto",
                    backgroundPosition: "0% 0%",
                    backgroundRepeat: "repeat"
                  }}
                >
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "LoginEditable__freeBox___7HVp"
                    )}
                    style={{
                      flexFlow: "row",
                      gridTemplateColumns: "none",
                      gridArea: "auto",
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%",
                      backgroundRepeat: "repeat"
                    }}
                  >
                    <Icon21Icon
                      className={classNames(
                        "plasmic_default__all",
                        "LoginEditable__svg__yckc"
                      )}
                      role={"img"}
                    />

                    <h1
                      data-plasmic-name={"h1"}
                      data-plasmic-override={overrides.h1}
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__h1",
                        "plasmic_default__h1__4WZ4j",
                        "LoginEditable__h1__kOmsg"
                      )}
                      style={{
                        flexFlow: "row",
                        gridTemplateColumns: "none",
                        gridArea: "auto",
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "LoginEditable__span__kVqbf"
                        )}
                      >
                        {"Continue sua jornada"}
                      </span>
                    </h1>
                    <p
                      data-plasmic-name={"p"}
                      data-plasmic-override={overrides.p}
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__p",
                        "plasmic_default__p__4WZ4j",
                        "LoginEditable__p__wNe5O"
                      )}
                      style={{
                        flexFlow: "row",
                        gridTemplateColumns: "none",
                        gridArea: "auto",
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "LoginEditable__span__flFov"
                        )}
                      >
                        {"Entre para continuar sua jornada."}
                      </span>
                    </p>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "LoginEditable__freeBox__qsA1X"
                    )}
                    style={{
                      flexFlow: "row",
                      gridTemplateColumns: "none",
                      gridArea: "auto",
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%",
                      backgroundRepeat: "repeat"
                    }}
                  >
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "LoginEditable__freeBox__ucbLg"
                      )}
                      style={{
                        flexFlow: "row",
                        gridTemplateColumns: "201.4px 201.4px",
                        gridArea: "auto",
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    >
                      <button
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__button",
                          "plasmic_default__button__4WZ4j",
                          "LoginEditable__button__qC7Ok"
                        )}
                        id={"radix-_R_59aq_-trigger-login"}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                        type={"button"}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "LoginEditable__span__webdG"
                          )}
                        >
                          {"Entrar"}
                        </span>
                      </button>
                      <button
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__button",
                          "plasmic_default__button__4WZ4j",
                          "LoginEditable__button__ocONx"
                        )}
                        id={"radix-_R_59aq_-trigger-signup"}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                        type={"button"}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "LoginEditable__span__tKrUs"
                          )}
                        >
                          {"Criar conta"}
                        </span>
                      </button>
                    </div>
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "LoginEditable__freeBox__en7Zj"
                      )}
                      id={"radix-_R_59aq_-content-login"}
                      style={{
                        flexFlow: "row",
                        gridTemplateColumns: "none",
                        gridArea: "auto",
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    >
                      <form
                        data-plasmic-name={"form"}
                        data-plasmic-override={overrides.form}
                        className={classNames(
                          "plasmic_default__all",
                          "LoginEditable__form___4QbJ"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <div
                          className={classNames(
                            "plasmic_default__all",
                            "LoginEditable__freeBox__bokzY"
                          )}
                          style={{
                            flexFlow: "row",
                            gridTemplateColumns: "none",
                            gridArea: "auto",
                            backgroundImage: "none",
                            backgroundSize: "auto",
                            backgroundPosition: "0% 0%",
                            backgroundRepeat: "repeat"
                          }}
                        >
                          <label
                            className={classNames(
                              "plasmic_default__all",
                              "LoginEditable__label__jor8"
                            )}
                            style={{
                              flexFlow: "row",
                              gridTemplateColumns: "none",
                              gridArea: "auto",
                              backgroundImage: "none",
                              backgroundSize: "auto",
                              backgroundPosition: "0% 0%",
                              backgroundRepeat: "repeat"
                            }}
                          >
                            <span
                              className={classNames(
                                "plasmic_default__all",
                                "plasmic_default__span",
                                "plasmic_default__span__4WZ4j",
                                "__wab_text",
                                "LoginEditable__span__pwExl"
                              )}
                            >
                              {"Email"}
                            </span>
                          </label>
                          <input
                            data-plasmic-name={"textbox"}
                            data-plasmic-override={overrides.textbox}
                            className={classNames(
                              "plasmic_default__all",
                              "plasmic_default__input",
                              "plasmic_default__input__4WZ4j",
                              "LoginEditable__textbox__y0Hvm"
                            )}
                            id={"login-email"}
                            name={"email"}
                            onChange={async (...eventArgs: any) => {
                              (e => {
                                generateStateOnChangeProp($state, [
                                  "textbox",
                                  "value"
                                ])(e.target.value);
                              }).apply(null, eventArgs);
                            }}
                            ref={ref => {
                              $refs["textbox"] = ref;
                            }}
                            style={{
                              flexFlow: "row",
                              gridTemplateColumns: "none",
                              gridArea: "auto",
                              backgroundImage: "none",
                              backgroundSize: "auto",
                              backgroundPosition: "0% 0%",
                              backgroundRepeat: "repeat"
                            }}
                            type={"email"}
                            value={
                              generateStateValueProp($state, [
                                "textbox",
                                "value"
                              ]) ?? ""
                            }
                          />
                        </div>
                        <div
                          className={classNames(
                            "plasmic_default__all",
                            "LoginEditable__freeBox__udidE"
                          )}
                          style={{
                            flexFlow: "row",
                            gridTemplateColumns: "none",
                            gridArea: "auto",
                            backgroundImage: "none",
                            backgroundSize: "auto",
                            backgroundPosition: "0% 0%",
                            backgroundRepeat: "repeat"
                          }}
                        >
                          <label
                            className={classNames(
                              "plasmic_default__all",
                              "LoginEditable__label__ehyam"
                            )}
                            style={{
                              flexFlow: "row",
                              gridTemplateColumns: "none",
                              gridArea: "auto",
                              backgroundImage: "none",
                              backgroundSize: "auto",
                              backgroundPosition: "0% 0%",
                              backgroundRepeat: "repeat"
                            }}
                          >
                            <span
                              className={classNames(
                                "plasmic_default__all",
                                "plasmic_default__span",
                                "plasmic_default__span__4WZ4j",
                                "__wab_text",
                                "LoginEditable__span__y5Fhh"
                              )}
                            >
                              {"Senha"}
                            </span>
                          </label>
                          <input
                            data-plasmic-name={"password"}
                            data-plasmic-override={overrides.password}
                            className={classNames(
                              "plasmic_default__all",
                              "plasmic_default__input",
                              "plasmic_default__input__4WZ4j",
                              "LoginEditable__password__zSrDs"
                            )}
                            id={"login-password"}
                            name={"password"}
                            onChange={async (...eventArgs: any) => {
                              (e => {
                                generateStateOnChangeProp($state, [
                                  "password",
                                  "value"
                                ])(e.target.value);
                              }).apply(null, eventArgs);
                            }}
                            ref={ref => {
                              $refs["password"] = ref;
                            }}
                            style={{
                              flexFlow: "row",
                              gridTemplateColumns: "none",
                              gridArea: "auto",
                              backgroundImage: "none",
                              backgroundSize: "auto",
                              backgroundPosition: "0% 0%",
                              backgroundRepeat: "repeat"
                            }}
                            type={"password"}
                            value={
                              generateStateValueProp($state, [
                                "password",
                                "value"
                              ]) ?? ""
                            }
                          />
                        </div>
                        <button
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__button",
                            "plasmic_default__button__4WZ4j",
                            "LoginEditable__button__w7Qy7"
                          )}
                          style={{
                            flexFlow: "row",
                            gridTemplateColumns: "none",
                            gridArea: "auto",
                            backgroundImage: "none",
                            backgroundSize: "auto",
                            backgroundPosition: "0% 0%",
                            backgroundRepeat: "repeat"
                          }}
                          type={"submit"}
                        >
                          <span
                            className={classNames(
                              "plasmic_default__all",
                              "plasmic_default__span",
                              "plasmic_default__span__4WZ4j",
                              "__wab_text",
                              "LoginEditable__span___8Yv84"
                            )}
                          >
                            {"Entrar"}
                          </span>
                        </button>
                      </form>
                    </div>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "LoginEditable__freeBox__gfFw"
                    )}
                    style={{
                      flexFlow: "row",
                      gridTemplateColumns: "none",
                      gridArea: "auto",
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%",
                      backgroundRepeat: "repeat"
                    }}
                  >
                    <PlasmicLink__
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__a",
                        "plasmic_default__a__4WZ4j",
                        "LoginEditable__link__dtytk"
                      )}
                      component={Link}
                      href={"/"}
                      platform={"tanstack"}
                      style={{
                        flexFlow: "row",
                        gridTemplateColumns: "none",
                        gridArea: "auto",
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "LoginEditable__span__g5IY"
                        )}
                      >
                        {"Voltar ao in\u00edcio"}
                      </span>
                    </PlasmicLink__>
                  </div>
                </div>
              </div>
            </div>
            <footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(
                "plasmic_default__all",
                "LoginEditable__footer__a7X4Z"
              )}
              style={{
                flexFlow: "row",
                gridTemplateColumns: "none",
                gridArea: "auto",
                backgroundImage: "none",
                backgroundSize: "auto",
                backgroundPosition: "0% 0%",
                backgroundRepeat: "repeat"
              }}
            >
              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "LoginEditable__span___7KK2Y"
                )}
                style={{
                  flexFlow: "row",
                  gridTemplateColumns: "none",
                  gridArea: "auto",
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%",
                  backgroundRepeat: "repeat"
                }}
              >
                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "__wab_text",
                    "LoginEditable__span__kSe1"
                  )}
                >
                  {'Kaizen \u2014 v0.1.0-alpha "Ember"'}
                </span>
              </span>
              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "LoginEditable__span__oFnJ4"
                )}
                style={{
                  flexFlow: "row",
                  gridTemplateColumns: "none",
                  gridArea: "auto",
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%",
                  backgroundRepeat: "repeat"
                }}
              >
                <Icon3Icon
                  className={classNames(
                    "plasmic_default__all",
                    "LoginEditable__svg__tbkLk"
                  )}
                  role={"img"}
                />

                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "__wab_text",
                    "LoginEditable__span__ppZGn"
                  )}
                >
                  {"Um passo de cada vez."}
                </span>
              </span>
            </footer>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "strong",
    "h1",
    "p",
    "form",
    "textbox",
    "password",
    "footer"
  ],
  header: ["header", "strong"],
  strong: ["strong"],
  h1: ["h1"],
  p: ["p"],
  form: ["form", "textbox", "password"],
  textbox: ["textbox"],
  password: ["password"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: "header";
  strong: "strong";
  h1: "h1";
  p: "p";
  form: "form";
  textbox: "input";
  password: "input";
  footer: "footer";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLoginEditable__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLoginEditable__VariantsArgs;
    args?: PlasmicLoginEditable__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicLoginEditable__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicLoginEditable__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicLoginEditable__ArgProps,
          internalVariantPropNames: PlasmicLoginEditable__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicLoginEditable__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLoginEditable";
  } else {
    func.displayName = `PlasmicLoginEditable.${nodeName}`;
  }
  return func;
}

export const PlasmicLoginEditable = Object.assign(
  // Top-level PlasmicLoginEditable renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    strong: makeNodeComponent("strong"),
    h1: makeNodeComponent("h1"),
    p: makeNodeComponent("p"),
    form: makeNodeComponent("form"),
    textbox: makeNodeComponent("textbox"),
    password: makeNodeComponent("password"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicLoginEditable
    internalVariantProps: PlasmicLoginEditable__VariantProps,
    internalArgProps: PlasmicLoginEditable__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/login-editable",
      pagePath: "/login-editable",
      params: {},
      query: {}
    })
  }
);

export const PlasmicLoginEditable__HeadOptions = {
  meta: [{ name: "twitter:card", content: "summary" }],

  links: []
} as Record<"meta" | "links", Array<Record<string, string>>>;

export default PlasmicLoginEditable;
/* prettier-ignore-end */
