/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4WZ4je7EqYHVjfVVU6jztT
// Component: dfGaMssLc0LU

import * as React from "react";

import { useRouter, Link } from "@tanstack/react-router";
import type { LinkProps } from "@tanstack/react-router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";
import "../../plasmic/plasmic__default_style.css"; // plasmic-import: global/defaultcss

import "./plasmic.css"; // plasmic-import: 4WZ4je7EqYHVjfVVU6jztT/projectcss
import "./PlasmicHomeEditable.css"; // plasmic-import: dfGaMssLc0LU/css

import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: 235GWjmNq59s/icon
import Icon6Icon from "./icons/PlasmicIcon__Icon6"; // plasmic-import: aEDZt3I3qYYl/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: Q6LIljTDGuwN/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: 8ALoWP7arWhs/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: yaKGkwJgSB1V/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: KmtymGVLw9CD/icon

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    openGraph: {},
    twitter: {
      card: "summary" as const
    }
  };
}

createPlasmicElementProxy;

export type PlasmicHomeEditable__VariantMembers = {};
export type PlasmicHomeEditable__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomeEditable__VariantsArgs;
export const PlasmicHomeEditable__VariantProps = new Array<VariantPropType>();

export type PlasmicHomeEditable__ArgsType = {};
type ArgPropType = keyof PlasmicHomeEditable__ArgsType;
export const PlasmicHomeEditable__ArgProps = new Array<ArgPropType>();

export type PlasmicHomeEditable__OverridesType = {
  root?: Flex__<"div">;
  header?: Flex__<"header">;
  button?: Flex__<"button">;
  main?: Flex__<"main">;
  i?: Flex__<"i">;
  h1?: Flex__<"h1">;
  em?: Flex__<"em">;
  footer?: Flex__<"footer">;
};

export interface DefaultHomeEditableProps {}

const $$ = {};

function useTanStackRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHomeEditable__RenderFunc(props: {
  variants: PlasmicHomeEditable__VariantsArgs;
  args: PlasmicHomeEditable__ArgsType;
  overrides: PlasmicHomeEditable__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __tanstackRouter = useTanStackRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={"plasmic_page_wrapper"}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "plasmic_default__all",
            "root_reset_4WZ4je7EqYHVjfVVU6jztT",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            "HomeEditable__root__ym6Ku"
          )}
        >
          <div
            className={classNames(
              "plasmic_default__all",
              "HomeEditable__freeBox__zEc0S"
            )}
            style={{
              flexFlow: "column",
              gridTemplateColumns: "none",
              gridArea: "auto",
              backgroundImage: "none",
              backgroundSize: "auto",
              backgroundPosition: "0% 0%",
              backgroundRepeat: "repeat"
            }}
          >
            <header
              data-plasmic-name={"header"}
              data-plasmic-override={overrides.header}
              className={classNames(
                "plasmic_default__all",
                "HomeEditable__header__jsOWw"
              )}
              style={{
                flexFlow: "row",
                gridTemplateColumns: "none",
                gridArea: "auto",
                backgroundImage: "none",
                backgroundSize: "auto",
                backgroundPosition: "0% 0%",
                backgroundRepeat: "repeat"
              }}
            >
              <PlasmicLink__
                aria-label={"Kaizen, in\u00edcio"}
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__a",
                  "plasmic_default__a__4WZ4j",
                  "HomeEditable__link__dynQm"
                )}
                component={Link}
                href={"/"}
                platform={"tanstack"}
                style={{
                  flexFlow: "row",
                  gridTemplateColumns: "none",
                  gridArea: "auto",
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%",
                  backgroundRepeat: "repeat"
                }}
              >
                <Icon3Icon
                  className={classNames(
                    "plasmic_default__all",
                    "HomeEditable__svg__pip2H"
                  )}
                  role={"img"}
                />

                <strong
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__strong",
                    "plasmic_default__strong__4WZ4j",
                    "HomeEditable__strong__ewRt7"
                  )}
                  style={{
                    flexFlow: "row",
                    gridTemplateColumns: "none",
                    gridArea: "auto",
                    backgroundImage: "none",
                    backgroundSize: "auto",
                    backgroundPosition: "0% 0%",
                    backgroundRepeat: "repeat"
                  }}
                >
                  <span
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__span",
                      "plasmic_default__span__4WZ4j",
                      "__wab_text",
                      "HomeEditable__span__dl1Sg"
                    )}
                  >
                    {"Kaizen"}
                  </span>
                </strong>
              </PlasmicLink__>
              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "HomeEditable__span__rZsIx"
                )}
                style={{
                  flexFlow: "row",
                  gridTemplateColumns: "none",
                  gridArea: "auto",
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%",
                  backgroundRepeat: "repeat"
                }}
              />

              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "HomeEditable__span__c3ECw"
                )}
                style={{
                  flexFlow: "row",
                  gridTemplateColumns: "none",
                  gridArea: "auto",
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%",
                  backgroundRepeat: "repeat"
                }}
              >
                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "__wab_text",
                    "HomeEditable__span___2RFca"
                  )}
                >
                  {"Ember"}
                </span>
              </span>
              <button
                data-plasmic-name={"button"}
                data-plasmic-override={overrides.button}
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__button",
                  "plasmic_default__button__4WZ4j",
                  "HomeEditable__button__b0R0I"
                )}
                style={{
                  flexFlow: "row",
                  gridTemplateColumns: "none",
                  gridArea: "auto",
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0px 0px",
                  backgroundRepeat: "repeat"
                }}
                type={"button"}
              >
                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "__wab_text",
                    "HomeEditable__span__voVt"
                  )}
                >
                  {"Sobre"}
                </span>
              </button>
              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "HomeEditable__span__kjyPd"
                )}
                style={{
                  flexFlow: "row",
                  gridTemplateColumns: "none",
                  gridArea: "auto",
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%",
                  backgroundRepeat: "repeat"
                }}
              >
                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "__wab_text",
                    "HomeEditable__span__asPvj"
                  )}
                >
                  {"v0.1.0-alpha"}
                </span>
              </span>
            </header>
            <main
              data-plasmic-name={"main"}
              data-plasmic-override={overrides.main}
              className={classNames(
                "plasmic_default__all",
                "HomeEditable__main___12Q3O"
              )}
              id={"main-content"}
              style={{
                flexFlow: "row",
                gridTemplateColumns: "none",
                gridArea: "auto",
                backgroundImage: "none",
                backgroundSize: "auto",
                backgroundPosition: "0% 0%",
                backgroundRepeat: "repeat"
              }}
            >
              <div
                className={classNames(
                  "plasmic_default__all",
                  "HomeEditable__freeBox__wzpQn"
                )}
                style={{
                  flexFlow: "row",
                  gridTemplateColumns: "none",
                  gridArea: "auto",
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%",
                  backgroundRepeat: "repeat"
                }}
              >
                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "HomeEditable__span__bdjXp"
                  )}
                  style={{
                    flexFlow: "row",
                    gridTemplateColumns: "none",
                    gridArea: "auto",
                    backgroundImage: "none",
                    backgroundSize: "auto",
                    backgroundPosition: "0% 0%",
                    backgroundRepeat: "repeat"
                  }}
                >
                  <span
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__span",
                      "plasmic_default__span__4WZ4j",
                      "__wab_text",
                      "HomeEditable__span__a13H7"
                    )}
                  >
                    {"KAIZEN PERSONAL SYSTEM"}
                  </span>
                </span>
                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "HomeEditable__span__f7N8X"
                  )}
                  style={{
                    flexFlow: "row",
                    gridTemplateColumns: "none",
                    gridArea: "auto",
                    backgroundImage: "none",
                    backgroundSize: "auto",
                    backgroundPosition: "0% 0%",
                    backgroundRepeat: "repeat"
                  }}
                >
                  <i
                    data-plasmic-name={"i"}
                    data-plasmic-override={overrides.i}
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__i",
                      "plasmic_default__i__4WZ4j",
                      "HomeEditable__i___0M1Hp"
                    )}
                    style={{
                      flexFlow: "row",
                      gridTemplateColumns: "none",
                      gridArea: "auto",
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%",
                      backgroundRepeat: "repeat"
                    }}
                  />

                  <span
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__span",
                      "plasmic_default__span__4WZ4j",
                      "__wab_text",
                      "HomeEditable__span__fSnTn"
                    )}
                  >
                    {"PRONTO PARA COME\u00c7AR"}
                  </span>
                </span>
              </div>
              <section
                className={classNames(
                  "plasmic_default__all",
                  "HomeEditable__section__y1N8"
                )}
                style={{
                  flexFlow: "row",
                  gridTemplateColumns: "none",
                  gridArea: "auto",
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%",
                  backgroundRepeat: "repeat"
                }}
              >
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "HomeEditable__freeBox__lhvMd"
                  )}
                  style={{
                    flexFlow: "row",
                    gridTemplateColumns: "none",
                    gridArea: "auto",
                    backgroundImage: "none",
                    backgroundSize: "auto",
                    backgroundPosition: "0% 0%",
                    backgroundRepeat: "repeat"
                  }}
                >
                  <p
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__p",
                      "plasmic_default__p__4WZ4j",
                      "HomeEditable__p__t00Yc"
                    )}
                    style={{
                      flexFlow: "row",
                      gridTemplateColumns: "none",
                      gridArea: "auto",
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%",
                      backgroundRepeat: "repeat"
                    }}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "HomeEditable__span__anrUf"
                      )}
                    >
                      {"um novo dia, um novo come\u00e7o."}
                    </span>
                  </p>
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__h1",
                      "plasmic_default__h1__4WZ4j",
                      "HomeEditable__h1__fuMuu"
                    )}
                    style={{
                      flexFlow: "row",
                      gridTemplateColumns: "none",
                      gridArea: "auto",
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%",
                      backgroundRepeat: "repeat"
                    }}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "HomeEditable__span__h59Ft"
                      )}
                    >
                      {"Pequenos passos."}
                    </span>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "HomeEditable__span__i3Nzw"
                      )}
                      style={{
                        flexFlow: "row",
                        gridTemplateColumns: "none",
                        gridArea: "auto",
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "HomeEditable__span__udetr"
                        )}
                      >
                        {"Grandes conquistas."}
                      </span>
                    </span>
                  </h1>
                </div>
                <div
                  className={classNames(
                    "plasmic_default__all",
                    "HomeEditable__freeBox__rnBLe"
                  )}
                  style={{
                    flexFlow: "row",
                    gridTemplateColumns: "none",
                    gridArea: "auto",
                    backgroundImage: "none",
                    backgroundSize: "auto",
                    backgroundPosition: "0% 0%",
                    backgroundRepeat: "repeat"
                  }}
                >
                  <span
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__span",
                      "plasmic_default__span__4WZ4j",
                      "__wab_text",
                      "HomeEditable__span__yA2X"
                    )}
                  >
                    {"K"}
                  </span>
                  <span
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__span",
                      "plasmic_default__span__4WZ4j",
                      "HomeEditable__span__k56B0"
                    )}
                    style={{
                      flexFlow: "row",
                      gridTemplateColumns: "none",
                      gridArea: "auto",
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%",
                      backgroundRepeat: "repeat"
                    }}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "HomeEditable__span__vJl1Q"
                      )}
                    >
                      {"+"}
                    </span>
                  </span>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "HomeEditable__freeBox___8Wum6"
                    )}
                    style={{
                      flexFlow: "row",
                      gridTemplateColumns: "none",
                      gridArea: "auto",
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%",
                      backgroundRepeat: "repeat"
                    }}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "__wab_text",
                        "HomeEditable__span__mOc6I"
                      )}
                    >
                      {"EST. 1997*"}
                    </span>
                  </div>
                </div>
              </section>
              <div
                className={classNames(
                  "plasmic_default__all",
                  "HomeEditable__freeBox___8AVDq"
                )}
                style={{
                  flexFlow: "row",
                  gridTemplateColumns: "517.138px 568.862px",
                  gridArea: "auto",
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%",
                  backgroundRepeat: "repeat"
                }}
              >
                <section
                  className={classNames(
                    "plasmic_default__all",
                    "HomeEditable__section__gDnp5"
                  )}
                  style={{
                    flexFlow: "row",
                    gridTemplateColumns: "none",
                    gridArea: "auto",
                    backgroundImage: "none",
                    backgroundSize: "auto",
                    backgroundPosition: "0% 0%",
                    backgroundRepeat: "repeat"
                  }}
                >
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "HomeEditable__freeBox___7HJqh"
                    )}
                    style={{
                      flexFlow: "row",
                      gridTemplateColumns: "none",
                      gridArea: "auto",
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%",
                      backgroundRepeat: "repeat"
                    }}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "HomeEditable__span__rgZdc"
                      )}
                      style={{
                        flexFlow: "row",
                        gridTemplateColumns: "none",
                        gridArea: "auto",
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    />

                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "HomeEditable__span__i5JCm"
                      )}
                      style={{
                        flexFlow: "row",
                        gridTemplateColumns: "none",
                        gridArea: "auto",
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "HomeEditable__span__hlMb1"
                        )}
                      >
                        {"bem-vindo.exe"}
                      </span>
                    </span>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "HomeEditable__span___2Vgxz"
                      )}
                      style={{
                        flexFlow: "row",
                        gridTemplateColumns: "none",
                        gridArea: "auto",
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "HomeEditable__span__psR1C"
                        )}
                      >
                        {"01"}
                      </span>
                    </span>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "HomeEditable__freeBox__cwCOz"
                    )}
                    style={{
                      flexFlow: "row",
                      gridTemplateColumns: "none",
                      gridArea: "auto",
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%",
                      backgroundRepeat: "repeat"
                    }}
                  >
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "HomeEditable__freeBox__uFnNh"
                      )}
                      style={{
                        flexFlow: "row",
                        gridTemplateColumns: "none",
                        gridArea: "auto",
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    >
                      <div
                        className={classNames(
                          "plasmic_default__all",
                          "HomeEditable__freeBox__svMxc"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "90px",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <Icon6Icon
                          className={classNames(
                            "plasmic_default__all",
                            "HomeEditable__svg__nzDjV"
                          )}
                          role={"img"}
                        />
                      </div>
                      <div
                        className={classNames(
                          "plasmic_default__all",
                          "HomeEditable__freeBox__yiAbb"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <strong
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__strong",
                            "plasmic_default__strong__4WZ4j",
                            "HomeEditable__strong__urwgN"
                          )}
                          style={{
                            flexFlow: "row",
                            gridTemplateColumns: "none",
                            gridArea: "auto",
                            backgroundImage: "none",
                            backgroundSize: "auto",
                            backgroundPosition: "0% 0%",
                            backgroundRepeat: "repeat"
                          }}
                        >
                          <span
                            className={classNames(
                              "plasmic_default__all",
                              "plasmic_default__span",
                              "plasmic_default__span__4WZ4j",
                              "__wab_text",
                              "HomeEditable__span__xhVdI"
                            )}
                          >
                            {"Kaizen"}
                          </span>
                        </strong>
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "HomeEditable__span__m0Wtq"
                          )}
                          style={{
                            flexFlow: "row",
                            gridTemplateColumns: "none",
                            gridArea: "auto",
                            backgroundImage: "none",
                            backgroundSize: "auto",
                            backgroundPosition: "0% 0%",
                            backgroundRepeat: "repeat"
                          }}
                        >
                          <span
                            className={classNames(
                              "plasmic_default__all",
                              "plasmic_default__span",
                              "plasmic_default__span__4WZ4j",
                              "__wab_text",
                              "HomeEditable__span__nUjgi"
                            )}
                          >
                            {"PERSONAL GROWTH SYSTEM"}
                          </span>
                        </span>
                      </div>
                    </div>
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "HomeEditable__freeBox__rw9Gw"
                      )}
                      style={{
                        flexFlow: "row",
                        gridTemplateColumns: "none",
                        gridArea: "auto",
                        backgroundImage:
                          "repeating-linear-gradient(0deg, rgb(163, 169, 156) 0px, rgb(163, 169, 156) 1px, rgba(0, 0, 0, 0) 1px, rgba(0, 0, 0, 0) 3px)",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    />

                    <p
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__p",
                        "plasmic_default__p__4WZ4j",
                        "HomeEditable__p__k2Ufi"
                      )}
                      style={{
                        flexFlow: "row",
                        gridTemplateColumns: "none",
                        gridArea: "auto",
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "HomeEditable__span__bRt4M"
                        )}
                      >
                        {"Sua pr\u00f3xima vers\u00e3o"}
                      </span>
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "HomeEditable__span___1IXf1"
                        )}
                      >
                        {"come\u00e7a"}
                      </span>
                      <em
                        data-plasmic-name={"em"}
                        data-plasmic-override={overrides.em}
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__em",
                          "plasmic_default__em__4WZ4j",
                          "HomeEditable__em__hpYpX"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "HomeEditable__span__ww0Cf"
                          )}
                        >
                          {"agora."}
                        </span>
                      </em>
                    </p>
                    <p
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__p",
                        "plasmic_default__p__4WZ4j",
                        "HomeEditable__p___3CY0E"
                      )}
                      style={{
                        flexFlow: "row",
                        gridTemplateColumns: "none",
                        gridArea: "auto",
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "HomeEditable__span__kVbmz"
                        )}
                      >
                        {
                          "Transforme tarefas em miss\u00f5es. Ganhe experi\u00eancia. Evolua no seu ritmo."
                        }
                      </span>
                    </p>
                    <PlasmicLink__
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__a",
                        "plasmic_default__a__4WZ4j",
                        "HomeEditable__link__doIu"
                      )}
                      component={Link}
                      href={"/auth"}
                      platform={"tanstack"}
                      style={{
                        flexFlow: "row",
                        gridTemplateColumns: "none",
                        gridArea: "auto",
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "HomeEditable__span__llKnn"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "36px",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <Icon3Icon
                          className={classNames(
                            "plasmic_default__all",
                            "HomeEditable__svg__m3MnJ"
                          )}
                          role={"img"}
                        />
                      </span>
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "HomeEditable__span__g4Hzt"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "HomeEditable__span__jtleK"
                          )}
                        >
                          {"Vamos come\u00e7ar"}
                        </span>
                        <div
                          className={classNames(
                            "plasmic_default__all",
                            "HomeEditable__freeBox__aQrq"
                          )}
                          style={{
                            flexFlow: "row",
                            gridTemplateColumns: "none",
                            gridArea: "auto",
                            backgroundImage: "none",
                            backgroundSize: "auto",
                            backgroundPosition: "0% 0%",
                            backgroundRepeat: "repeat"
                          }}
                        >
                          <span
                            className={classNames(
                              "plasmic_default__all",
                              "plasmic_default__span",
                              "plasmic_default__span__4WZ4j",
                              "__wab_text",
                              "HomeEditable__span__flCOp"
                            )}
                          >
                            {"Entre ou crie seu personagem"}
                          </span>
                        </div>
                      </span>
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "HomeEditable__span__tP0S"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "HomeEditable__span__jcsrr"
                          )}
                        >
                          {"\u2197"}
                        </span>
                      </span>
                    </PlasmicLink__>
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "HomeEditable__freeBox__vqv86"
                      )}
                      style={{
                        flexFlow: "row",
                        gridTemplateColumns: "none",
                        gridArea: "auto",
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "HomeEditable__span__idKoX"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "HomeEditable__span___1JaTd"
                          )}
                        >
                          {"\u25cf EMBER EDITION"}
                        </span>
                      </span>
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "HomeEditable__span__qujj"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "HomeEditable__span__aEyQo"
                          )}
                        >
                          {"v0.1.0-alpha"}
                        </span>
                      </span>
                    </div>
                  </div>
                </section>
                <section
                  aria-label={"Explore seu sistema"}
                  className={classNames(
                    "plasmic_default__all",
                    "HomeEditable__section__gX7BH"
                  )}
                  style={{
                    flexFlow: "row",
                    gridTemplateColumns: "none",
                    gridArea: "auto",
                    backgroundImage: "none",
                    backgroundSize: "auto",
                    backgroundPosition: "0% 0%",
                    backgroundRepeat: "repeat"
                  }}
                >
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "HomeEditable__freeBox__chN8J"
                    )}
                    style={{
                      flexFlow: "row",
                      gridTemplateColumns: "none",
                      gridArea: "auto",
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%",
                      backgroundRepeat: "repeat"
                    }}
                  >
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "HomeEditable__span__ozKro"
                      )}
                      style={{
                        flexFlow: "row",
                        gridTemplateColumns: "none",
                        gridArea: "auto",
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "HomeEditable__span__pKLqZ"
                        )}
                      >
                        {"seu mundo, em movimento"}
                      </span>
                    </span>
                    <span
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__span",
                        "plasmic_default__span__4WZ4j",
                        "HomeEditable__span__oxRUz"
                      )}
                      style={{
                        flexFlow: "row",
                        gridTemplateColumns: "none",
                        gridArea: "auto",
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "__wab_text",
                          "HomeEditable__span__iEn"
                        )}
                      >
                        {"\u2193"}
                      </span>
                    </span>
                  </div>
                  <div
                    className={classNames(
                      "plasmic_default__all",
                      "HomeEditable__freeBox__nPmtA"
                    )}
                    style={{
                      flexFlow: "row",
                      gridTemplateColumns: "277.425px 277.438px",
                      gridArea: "auto",
                      backgroundImage: "none",
                      backgroundSize: "auto",
                      backgroundPosition: "0% 0%",
                      backgroundRepeat: "repeat"
                    }}
                  >
                    <PlasmicLink__
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__a",
                        "plasmic_default__a__4WZ4j",
                        "HomeEditable__link__fbKv"
                      )}
                      component={Link}
                      href={"/auth"}
                      platform={"tanstack"}
                      style={{
                        flexFlow: "column",
                        gridTemplateColumns: "none",
                        gridArea: "auto",
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "HomeEditable__span__tXqb5"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "HomeEditable__span__coh7B"
                          )}
                        >
                          {"01 / FAZER"}
                        </span>
                      </span>
                      <IconIcon
                        className={classNames(
                          "plasmic_default__all",
                          "HomeEditable__svg___80KJy"
                        )}
                        role={"img"}
                      />

                      <strong
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__strong",
                          "plasmic_default__strong__4WZ4j",
                          "HomeEditable__strong__rx8Yr"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "HomeEditable__span__dDPg3"
                          )}
                        >
                          {"miss\u00f5es"}
                        </span>
                      </strong>
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "HomeEditable__span__cWb"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "HomeEditable__span___6ARqu"
                          )}
                        >
                          {"Um passo de cada vez."}
                        </span>
                      </span>
                      <b
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__b",
                          "plasmic_default__b__4WZ4j",
                          "HomeEditable__b__jWze"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "HomeEditable__span__oZzpz"
                          )}
                        >
                          {"\u2197"}
                        </span>
                      </b>
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__a",
                        "plasmic_default__a__4WZ4j",
                        "HomeEditable__link__gaMnw"
                      )}
                      component={Link}
                      href={"/auth"}
                      platform={"tanstack"}
                      style={{
                        flexFlow: "column",
                        gridTemplateColumns: "none",
                        gridArea: "auto",
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "HomeEditable__span__y5Ql"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "HomeEditable__span__r8Cz7"
                          )}
                        >
                          {"02 / CRESCER"}
                        </span>
                      </span>
                      <Icon5Icon
                        className={classNames(
                          "plasmic_default__all",
                          "HomeEditable__svg__ewisT"
                        )}
                        role={"img"}
                      />

                      <strong
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__strong",
                          "plasmic_default__strong__4WZ4j",
                          "HomeEditable__strong__ntq30"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "HomeEditable__span___0UbEk"
                          )}
                        >
                          {"progresso"}
                        </span>
                      </strong>
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "HomeEditable__span__xm8Ej"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "HomeEditable__span__ynVfe"
                          )}
                        >
                          {"Cada conquista conta."}
                        </span>
                      </span>
                      <b
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__b",
                          "plasmic_default__b__4WZ4j",
                          "HomeEditable__b__nuCpQ"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "HomeEditable__span__kShW"
                          )}
                        >
                          {"\u2197"}
                        </span>
                      </b>
                    </PlasmicLink__>
                    <PlasmicLink__
                      className={classNames(
                        "plasmic_default__all",
                        "plasmic_default__a",
                        "plasmic_default__a__4WZ4j",
                        "HomeEditable__link__ubqxb"
                      )}
                      component={Link}
                      href={"/auth"}
                      platform={"tanstack"}
                      style={{
                        flexFlow: "column",
                        gridTemplateColumns: "none",
                        gridArea: "auto",
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    >
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "HomeEditable__span___04M9"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "HomeEditable__span__tNzA0"
                          )}
                        >
                          {"03 / SER"}
                        </span>
                      </span>
                      <Icon2Icon
                        className={classNames(
                          "plasmic_default__all",
                          "HomeEditable__svg__jj9LY"
                        )}
                        role={"img"}
                      />

                      <strong
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__strong",
                          "plasmic_default__strong__4WZ4j",
                          "HomeEditable__strong__qQiNj"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "HomeEditable__span__hlKL"
                          )}
                        >
                          {"personagem"}
                        </span>
                      </strong>
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "HomeEditable__span___58Wc"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "HomeEditable__span__s5RQz"
                          )}
                        >
                          {"Conhe\u00e7a sua melhor vers\u00e3o."}
                        </span>
                      </span>
                      <b
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__b",
                          "plasmic_default__b__4WZ4j",
                          "HomeEditable__b___7OWjE"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "HomeEditable__span___7UfQ1"
                          )}
                        >
                          {"\u2197"}
                        </span>
                      </b>
                    </PlasmicLink__>
                    <div
                      className={classNames(
                        "plasmic_default__all",
                        "HomeEditable__freeBox__xlssd"
                      )}
                      style={{
                        flexFlow: "column",
                        gridTemplateColumns: "none",
                        gridArea: "auto",
                        backgroundImage: "none",
                        backgroundSize: "auto",
                        backgroundPosition: "0% 0%",
                        backgroundRepeat: "repeat"
                      }}
                    >
                      <div
                        className={classNames(
                          "plasmic_default__all",
                          "HomeEditable__freeBox__c1It1"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <Icon4Icon
                          className={classNames(
                            "plasmic_default__all",
                            "HomeEditable__svg__fB58"
                          )}
                          role={"img"}
                        />

                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "HomeEditable__span__u82Ie"
                          )}
                          style={{
                            flexFlow: "row",
                            gridTemplateColumns: "none",
                            gridArea: "auto",
                            backgroundImage: "none",
                            backgroundSize: "auto",
                            backgroundPosition: "0% 0%",
                            backgroundRepeat: "repeat"
                          }}
                        >
                          <span
                            className={classNames(
                              "plasmic_default__all",
                              "plasmic_default__span",
                              "plasmic_default__span__4WZ4j",
                              "__wab_text",
                              "HomeEditable__span___0G9Oi"
                            )}
                          >
                            {"lembrete.txt"}
                          </span>
                        </span>
                      </div>
                      <p
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__p",
                          "plasmic_default__p__4WZ4j",
                          "HomeEditable__p__y9ZCu"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "HomeEditable__span__ikYx5"
                          )}
                        >
                          {"Voc\u00ea n\u00e3o precisa"}
                        </span>
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "HomeEditable__span__okSwx"
                          )}
                        >
                          {"fazer tudo hoje."}
                        </span>
                        <strong
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__strong",
                            "plasmic_default__strong__4WZ4j",
                            "HomeEditable__strong__jnmPp"
                          )}
                          style={{
                            flexFlow: "row",
                            gridTemplateColumns: "none",
                            gridArea: "auto",
                            backgroundImage: "none",
                            backgroundSize: "auto",
                            backgroundPosition: "0% 0%",
                            backgroundRepeat: "repeat"
                          }}
                        >
                          <span
                            className={classNames(
                              "plasmic_default__all",
                              "plasmic_default__span",
                              "plasmic_default__span__4WZ4j",
                              "__wab_text",
                              "HomeEditable__span__pTi9R"
                            )}
                          >
                            {"S\u00f3 come\u00e7ar."}
                          </span>
                        </strong>
                      </p>
                      <span
                        className={classNames(
                          "plasmic_default__all",
                          "plasmic_default__span",
                          "plasmic_default__span__4WZ4j",
                          "HomeEditable__span__zpqfS"
                        )}
                        style={{
                          flexFlow: "row",
                          gridTemplateColumns: "none",
                          gridArea: "auto",
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "0% 0%",
                          backgroundRepeat: "repeat"
                        }}
                      >
                        <span
                          className={classNames(
                            "plasmic_default__all",
                            "plasmic_default__span",
                            "plasmic_default__span__4WZ4j",
                            "__wab_text",
                            "HomeEditable__span__vUmjc"
                          )}
                        >
                          {"salvo para voc\u00ea \u2665"}
                        </span>
                      </span>
                    </div>
                  </div>
                </section>
              </div>
              <div
                className={classNames(
                  "plasmic_default__all",
                  "HomeEditable__freeBox__mkebr"
                )}
                style={{
                  flexFlow: "row",
                  gridTemplateColumns: "none",
                  gridArea: "auto",
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%",
                  backgroundRepeat: "repeat"
                }}
              >
                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "HomeEditable__span___1W7Jr"
                  )}
                  style={{
                    flexFlow: "row",
                    gridTemplateColumns: "none",
                    gridArea: "auto",
                    backgroundImage: "none",
                    backgroundSize: "auto",
                    backgroundPosition: "0% 0%",
                    backgroundRepeat: "repeat"
                  }}
                >
                  <span
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__span",
                      "plasmic_default__span__4WZ4j",
                      "__wab_text",
                      "HomeEditable__span__aeeC"
                    )}
                  >
                    {"FEITO PARA A VIDA REAL. E PARA O SEU BOLSO."}
                  </span>
                </span>
                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "HomeEditable__span___0WZww"
                  )}
                  style={{
                    flexFlow: "row",
                    gridTemplateColumns: "none",
                    gridArea: "auto",
                    backgroundImage: "none",
                    backgroundSize: "auto",
                    backgroundPosition: "0% 0%",
                    backgroundRepeat: "repeat"
                  }}
                >
                  <span
                    className={classNames(
                      "plasmic_default__all",
                      "plasmic_default__span",
                      "plasmic_default__span__4WZ4j",
                      "__wab_text",
                      "HomeEditable__span__q4Ol"
                    )}
                  >
                    {"* nostalgia de 1997. possibilidades de hoje."}
                  </span>
                </span>
              </div>
            </main>
            <footer
              data-plasmic-name={"footer"}
              data-plasmic-override={overrides.footer}
              className={classNames(
                "plasmic_default__all",
                "HomeEditable__footer__gysbD"
              )}
              style={{
                flexFlow: "row",
                gridTemplateColumns: "none",
                gridArea: "auto",
                backgroundImage: "none",
                backgroundSize: "auto",
                backgroundPosition: "0% 0%",
                backgroundRepeat: "repeat"
              }}
            >
              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "HomeEditable__span__ymyFy"
                )}
                style={{
                  flexFlow: "row",
                  gridTemplateColumns: "none",
                  gridArea: "auto",
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%",
                  backgroundRepeat: "repeat"
                }}
              >
                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "__wab_text",
                    "HomeEditable__span__oYaL"
                  )}
                >
                  {'Kaizen \u2014 v0.1.0-alpha "Ember"'}
                </span>
              </span>
              <span
                className={classNames(
                  "plasmic_default__all",
                  "plasmic_default__span",
                  "plasmic_default__span__4WZ4j",
                  "HomeEditable__span__ngzsw"
                )}
                style={{
                  flexFlow: "row",
                  gridTemplateColumns: "none",
                  gridArea: "auto",
                  backgroundImage: "none",
                  backgroundSize: "auto",
                  backgroundPosition: "0% 0%",
                  backgroundRepeat: "repeat"
                }}
              >
                <Icon3Icon
                  className={classNames(
                    "plasmic_default__all",
                    "HomeEditable__svg___25H"
                  )}
                  role={"img"}
                />

                <span
                  className={classNames(
                    "plasmic_default__all",
                    "plasmic_default__span",
                    "plasmic_default__span__4WZ4j",
                    "__wab_text",
                    "HomeEditable__span__ufR0P"
                  )}
                >
                  {"Um passo de cada vez."}
                </span>
              </span>
            </footer>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "button", "main", "i", "h1", "em", "footer"],
  header: ["header", "button"],
  button: ["button"],
  main: ["main", "i", "h1", "em"],
  i: ["i"],
  h1: ["h1"],
  em: ["em"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: "header";
  button: "button";
  main: "main";
  i: "i";
  h1: "h1";
  em: "em";
  footer: "footer";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomeEditable__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomeEditable__VariantsArgs;
    args?: PlasmicHomeEditable__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHomeEditable__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHomeEditable__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomeEditable__ArgProps,
          internalVariantPropNames: PlasmicHomeEditable__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomeEditable__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomeEditable";
  } else {
    func.displayName = `PlasmicHomeEditable.${nodeName}`;
  }
  return func;
}

export const PlasmicHomeEditable = Object.assign(
  // Top-level PlasmicHomeEditable renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    button: makeNodeComponent("button"),
    main: makeNodeComponent("main"),
    i: makeNodeComponent("i"),
    h1: makeNodeComponent("h1"),
    em: makeNodeComponent("em"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicHomeEditable
    internalVariantProps: PlasmicHomeEditable__VariantProps,
    internalArgProps: PlasmicHomeEditable__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/home-editable",
      pagePath: "/home-editable",
      params: {},
      query: {}
    })
  }
);

export const PlasmicHomeEditable__HeadOptions = {
  meta: [{ name: "twitter:card", content: "summary" }],

  links: []
} as Record<"meta" | "links", Array<Record<string, string>>>;

export default PlasmicHomeEditable;
/* prettier-ignore-end */
